// Generated by wit-js-bindgen 0.0.1 — do not edit.
// world: libduckdb

export interface Decimalvalue {
    lower: bigint;
    upper: bigint;
    width: number;
    scale: number;
}

export interface Intervalvalue {
    months: number;
    days: number;
    micros: bigint;
}

export interface Uuidvalue {
    hi: bigint;
    lo: bigint;
}

export interface Complexvalue {
    typeExpr: string;
    json: string;
}

export interface DuckInt128 {
    lower: bigint;
    upper: bigint;
}

export interface DuckUint128 {
    lower: bigint;
    upper: bigint;
}

export interface NestedColumn {
    encoded: number[];
}

export interface MapColumn {
    keysEncoded: number[];
    valsEncoded: number[];
}

export interface ArrayColumn {
    size: number;
    encoded: number[];
}

export type Column = { tag: "boolean", val: boolean[] } | { tag: "int64", val: bigint[] } | { tag: "uint64", val: bigint[] } | { tag: "float64", val: number[] } | { tag: "int32", val: number[] } | { tag: "timestamp", val: bigint[] } | { tag: "int8", val: number[] } | { tag: "int16", val: number[] } | { tag: "uint8", val: number[] } | { tag: "uint16", val: number[] } | { tag: "uint32", val: number[] } | { tag: "float32", val: number[] } | { tag: "date", val: number[] } | { tag: "time", val: bigint[] } | { tag: "timestamptz", val: bigint[] } | { tag: "decimal", val: Decimalvalue[] } | { tag: "interval", val: Intervalvalue[] } | { tag: "uuid", val: Uuidvalue[] } | { tag: "text", val: string[] } | { tag: "blob", val: number[][] } | { tag: "hugeint", val: DuckInt128[] } | { tag: "uhugeint", val: DuckUint128[] } | { tag: "list-col", val: NestedColumn } | { tag: "struct-col", val: NestedColumn } | { tag: "map-col", val: MapColumn } | { tag: "array-col", val: ArrayColumn } | { tag: "complex", val: Complexvalue[] };

export interface Colvec {
    data: Column;
    validity: number[];
    rows: number;
}

export interface Decimalshape {
    width: number;
    scale: number;
}

export type Logicaltype = { tag: "boolean" } | { tag: "int64" } | { tag: "uint64" } | { tag: "float64" } | { tag: "text" } | { tag: "blob" } | { tag: "int32" } | { tag: "timestamp" } | { tag: "int8" } | { tag: "int16" } | { tag: "uint8" } | { tag: "uint16" } | { tag: "uint32" } | { tag: "float32" } | { tag: "date" } | { tag: "time" } | { tag: "timestamptz" } | { tag: "decimal", val: Decimalshape } | { tag: "interval" } | { tag: "uuid" } | { tag: "hugeint" } | { tag: "uhugeint" } | { tag: "complex", val: string };

export interface Hugeintvalue {
    lower: bigint;
    upper: bigint;
}

export interface Uhugeintvalue {
    lower: bigint;
    upper: bigint;
}

export interface Funcarg {
    name: string | undefined;
    logical: Logicaltype;
}

export interface Funcflags {
    deterministic: boolean;
    commutative: boolean;
    stateless: boolean;
    sideeffecting: boolean;
    deprecated: boolean;
}

export interface Funcopts {
    description: string | undefined;
    tags: string[];
    attributes: Funcflags;
}

export interface Columndef {
    name: string;
    logical: Logicaltype;
}

export interface Extopts {
    description: string | undefined;
    tags: string[];
}

export type Duckvalue = { tag: "null" } | { tag: "boolean", val: boolean } | { tag: "int64", val: bigint } | { tag: "uint64", val: bigint } | { tag: "float64", val: number } | { tag: "text", val: string } | { tag: "blob", val: number[] } | { tag: "int32", val: number } | { tag: "timestamp", val: bigint } | { tag: "int8", val: number } | { tag: "int16", val: number } | { tag: "uint8", val: number } | { tag: "uint16", val: number } | { tag: "uint32", val: number } | { tag: "float32", val: number } | { tag: "date", val: number } | { tag: "time", val: bigint } | { tag: "timestamptz", val: bigint } | { tag: "decimal", val: Decimalvalue } | { tag: "interval", val: Intervalvalue } | { tag: "uuid", val: Uuidvalue } | { tag: "hugeint", val: Hugeintvalue } | { tag: "uhugeint", val: Uhugeintvalue } | { tag: "complex", val: Complexvalue };

export type Resultset = Duckvalue[][];

export type Rowbatch = Duckvalue[][];

export interface Invokeinfo {
    rowindex: bigint | undefined;
    iswindow: boolean;
}

export type Duckerror = { tag: "invalidargument", val: string } | { tag: "unsupported", val: string } | { tag: "invalidstate", val: string } | { tag: "io", val: string } | { tag: "internal", val: string };

export type Configerror = { tag: "invalidkey", val: string } | { tag: "typemismatch", val: string } | { tag: "unavailable", val: string } | { tag: "internalconfig", val: string };

export type Loglevel = "trace" | "debug" | "info" | "warn" | "error";

export interface Logfield {
    key: string;
    value: string;
}

export type Capabilitykind = "scalar" | "table" | "aggregate" | "pragma" | "macro" | "catalog" | "file-format";

export interface Loadresult {
    name: string;
    version: string | undefined;
    requires: Capabilitykind[];
}

export type Capability = { tag: "scalar", val: ScalarRegistry } | { tag: "table", val: TableRegistry } | { tag: "aggregate", val: AggregateRegistry } | { tag: "pragma", val: PragmaRegistry } | { tag: "macro", val: MacroRegistry };

export type StreamError = { tag: "last-operation-failed", val: Error } | { tag: "closed" };

export interface Datetime {
    seconds: bigint;
    nanoseconds: number;
}

export type Filesize = bigint;

export type DescriptorType = "unknown" | "block-device" | "character-device" | "directory" | "fifo" | "symbolic-link" | "regular-file" | "socket";

export interface DescriptorFlags {
    read: boolean;
    write: boolean;
    fileIntegritySync: boolean;
    dataIntegritySync: boolean;
    requestedWriteSync: boolean;
    mutateDirectory: boolean;
}

export interface PathFlags {
    symlinkFollow: boolean;
}

export interface OpenFlags {
    create: boolean;
    directory: boolean;
    exclusive: boolean;
    truncate: boolean;
}

export type LinkCount = bigint;

export interface DescriptorStat {
    type: DescriptorType;
    linkCount: LinkCount;
    size: Filesize;
    dataAccessTimestamp: Datetime | undefined;
    dataModificationTimestamp: Datetime | undefined;
    statusChangeTimestamp: Datetime | undefined;
}

export type NewTimestamp = { tag: "no-change" } | { tag: "now" } | { tag: "timestamp", val: Datetime };

export interface DirectoryEntry {
    type: DescriptorType;
    name: string;
}

export type ErrorCode = "access" | "would-block" | "already" | "bad-descriptor" | "busy" | "deadlock" | "quota" | "exist" | "file-too-large" | "illegal-byte-sequence" | "in-progress" | "interrupted" | "invalid" | "io" | "is-directory" | "loop" | "too-many-links" | "message-size" | "name-too-long" | "no-device" | "no-entry" | "no-lock" | "insufficient-memory" | "insufficient-space" | "not-directory" | "not-empty" | "not-recoverable" | "unsupported" | "no-tty" | "no-such-device" | "overflow" | "not-permitted" | "pipe" | "read-only" | "invalid-seek" | "text-file-busy" | "cross-device";

export type Advice = "normal" | "sequential" | "random" | "will-need" | "dont-need" | "no-reuse";

export interface MetadataHashValue {
    lower: bigint;
    upper: bigint;
}

export type RegionKind = "hot-heap" | "object-arena" | "blob-arena" | "page-store" | "scratch" | "device-state" | "code-cache";

export type Residency = "hot" | "warm" | "cold" | "external";

export interface Handle {
    regionId: number;
    generation: number;
    offset: number;
}

export interface RegionInfo {
    id: number;
    generation: number;
    kind: RegionKind;
    capacity: number;
    used: number;
    residency: Residency;
}

export type TvmError = { tag: "region-not-found", val: number } | { tag: "stale-handle" } | { tag: "out-of-bounds" } | { tag: "not-resident" } | { tag: "allocation-failed" } | { tag: "backing-store", val: string } | { tag: "pinned" };

export interface ColumnDescriptor {
    name: string;
    ty: Logicaltype;
}

export type Row = Duckvalue[];

export interface QueryResult {
    columns: Columndef[];
    rows: Row[];
}

export interface ExtensionInfo {
    name: string;
    requires: Capabilitykind[];
}

export interface UiResponse {
    status: number;
    headers: string;
    body: number[];
}

export interface FuncArg {
    name: string | undefined;
    logical: Logicaltype;
}

export interface FuncOpts {
    description: string | undefined;
    tags: string[];
    attributes: Funcflags;
}

export interface ExtOpts {
    description: string | undefined;
    tags: string[];
}

export interface ScalarRegistration {
    name: string;
    arguments: FuncArg[];
    returns: Logicaltype;
    callbackHandle: number;
    options: FuncOpts | undefined;
}

export interface TableRegistration {
    name: string;
    arguments: FuncArg[];
    columns: Columndef[];
    callbackHandle: number;
    options: ExtOpts | undefined;
}

export interface AggregateRegistration {
    name: string;
    arguments: FuncArg[];
    returns: Logicaltype;
    callbackHandle: number;
    options: FuncOpts | undefined;
}

export interface MacroRegistration {
    schema: string;
    name: string;
    parameters: string[];
    definitionSql: string;
}

export interface ReplacementScanRegistration {
    extensions: string[];
    functionName: string;
}

export interface LogicalTypeRegistration {
    name: string;
    physical: string;
}

export interface CastRegistration {
    source: string;
    target: string;
    callbackHandle: number;
}

export interface PendingRegistrations {
    scalars: ScalarRegistration[];
    tables: TableRegistration[];
    aggregates: AggregateRegistration[];
    macros: MacroRegistration[];
    replacementScans: ReplacementScanRegistration[];
    logicalTypes: LogicalTypeRegistration[];
    casts: CastRegistration[];
}

export class AggregateCallback {
    constructor(handle: number);
    call(rows: Rowbatch): { tag: "ok", val: Duckvalue } | { tag: "err", val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class AggregateRegistry {
    register(name: string, arguments: Funcarg[], returns: Logicaltype, callback: AggregateCallback, options: Funcopts | undefined): { tag: "ok", val: number } | { tag: "err", val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class Appender {
    appendRow(values: Duckvalue[]): { tag: "ok" } | { tag: "err", val: Duckerror };
    close(): { tag: "ok" } | { tag: "err", val: Duckerror };
    flush(): { tag: "ok" } | { tag: "err", val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class CastCallback {
    constructor(handle: number);
    call(value: Duckvalue): { tag: "ok", val: Duckvalue } | { tag: "err", val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class Connection {
    drop(): void;
    [Symbol.dispose](): void;
}

export interface DescriptorInstance {
    advise(offset: Filesize, length: Filesize, advice: Advice): { tag: "ok" } | { tag: "err", val: ErrorCode };
    appendViaStream(): { tag: "ok", val: OutputStream } | { tag: "err", val: ErrorCode };
    createDirectoryAt(path: string): { tag: "ok" } | { tag: "err", val: ErrorCode };
    getFlags(): { tag: "ok", val: DescriptorFlags } | { tag: "err", val: ErrorCode };
    getType(): { tag: "ok", val: DescriptorType } | { tag: "err", val: ErrorCode };
    isSameObject(other: DescriptorInstance): boolean;
    linkAt(oldPathFlags: PathFlags, oldPath: string, newDescriptor: DescriptorInstance, newPath: string): { tag: "ok" } | { tag: "err", val: ErrorCode };
    metadataHash(): { tag: "ok", val: MetadataHashValue } | { tag: "err", val: ErrorCode };
    metadataHashAt(pathFlags: PathFlags, path: string): { tag: "ok", val: MetadataHashValue } | { tag: "err", val: ErrorCode };
    openAt(pathFlags: PathFlags, path: string, openFlags: OpenFlags, flags: DescriptorFlags): { tag: "ok", val: DescriptorInstance } | { tag: "err", val: ErrorCode };
    read(length: Filesize, offset: Filesize): { tag: "ok", val: [number[], boolean] } | { tag: "err", val: ErrorCode };
    readDirectory(): { tag: "ok", val: DirectoryEntryStreamInstance } | { tag: "err", val: ErrorCode };
    readViaStream(offset: Filesize): { tag: "ok", val: InputStream } | { tag: "err", val: ErrorCode };
    readlinkAt(path: string): { tag: "ok", val: string } | { tag: "err", val: ErrorCode };
    removeDirectoryAt(path: string): { tag: "ok" } | { tag: "err", val: ErrorCode };
    renameAt(oldPath: string, newDescriptor: DescriptorInstance, newPath: string): { tag: "ok" } | { tag: "err", val: ErrorCode };
    setSize(size: Filesize): { tag: "ok" } | { tag: "err", val: ErrorCode };
    setTimes(dataAccessTimestamp: NewTimestamp, dataModificationTimestamp: NewTimestamp): { tag: "ok" } | { tag: "err", val: ErrorCode };
    setTimesAt(pathFlags: PathFlags, path: string, dataAccessTimestamp: NewTimestamp, dataModificationTimestamp: NewTimestamp): { tag: "ok" } | { tag: "err", val: ErrorCode };
    stat(): { tag: "ok", val: DescriptorStat } | { tag: "err", val: ErrorCode };
    statAt(pathFlags: PathFlags, path: string): { tag: "ok", val: DescriptorStat } | { tag: "err", val: ErrorCode };
    symlinkAt(oldPath: string, newPath: string): { tag: "ok" } | { tag: "err", val: ErrorCode };
    sync(): { tag: "ok" } | { tag: "err", val: ErrorCode };
    syncData(): { tag: "ok" } | { tag: "err", val: ErrorCode };
    unlinkFileAt(path: string): { tag: "ok" } | { tag: "err", val: ErrorCode };
    write(buffer: number[], offset: Filesize): { tag: "ok", val: Filesize } | { tag: "err", val: ErrorCode };
    writeViaStream(offset: Filesize): { tag: "ok", val: OutputStream } | { tag: "err", val: ErrorCode };
    [Symbol.dispose]?(): void;
    drop?(): void;
}

export interface DescriptorConstructor {
    new (): DescriptorInstance;
}

export interface DirectoryEntryStreamInstance {
    readDirectoryEntry(): { tag: "ok", val: DirectoryEntry | undefined } | { tag: "err", val: ErrorCode };
    [Symbol.dispose]?(): void;
    drop?(): void;
}

export interface DirectoryEntryStreamConstructor {
    new (): DirectoryEntryStreamInstance;
}

export interface ErrorInstance {
    toDebugString(): string;
    [Symbol.dispose]?(): void;
    drop?(): void;
}

export interface ErrorConstructor {
    new (): ErrorInstance;
}

export interface InputStreamInstance {
    blockingRead(len: bigint): { tag: "ok", val: number[] } | { tag: "err", val: StreamError };
    blockingSkip(len: bigint): { tag: "ok", val: bigint } | { tag: "err", val: StreamError };
    read(len: bigint): { tag: "ok", val: number[] } | { tag: "err", val: StreamError };
    skip(len: bigint): { tag: "ok", val: bigint } | { tag: "err", val: StreamError };
    subscribe(): Pollable;
    [Symbol.dispose]?(): void;
    drop?(): void;
}

export interface InputStreamConstructor {
    new (): InputStreamInstance;
}

export class MacroRegistry {
    registerScalar(name: string, parameters: string[], bodySql: string, options: Extopts | undefined): { tag: "ok", val: boolean } | { tag: "err", val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export interface OutputStreamInstance {
    blockingFlush(): { tag: "ok" } | { tag: "err", val: StreamError };
    blockingSplice(src: InputStreamInstance, len: bigint): { tag: "ok", val: bigint } | { tag: "err", val: StreamError };
    blockingWriteAndFlush(contents: number[]): { tag: "ok" } | { tag: "err", val: StreamError };
    blockingWriteZeroesAndFlush(len: bigint): { tag: "ok" } | { tag: "err", val: StreamError };
    checkWrite(): { tag: "ok", val: bigint } | { tag: "err", val: StreamError };
    flush(): { tag: "ok" } | { tag: "err", val: StreamError };
    splice(src: InputStreamInstance, len: bigint): { tag: "ok", val: bigint } | { tag: "err", val: StreamError };
    subscribe(): Pollable;
    write(contents: number[]): { tag: "ok" } | { tag: "err", val: StreamError };
    writeZeroes(len: bigint): { tag: "ok" } | { tag: "err", val: StreamError };
    [Symbol.dispose]?(): void;
    drop?(): void;
}

export interface OutputStreamConstructor {
    new (): OutputStreamInstance;
}

export interface PollableInstance {
    block(): void;
    ready(): boolean;
    [Symbol.dispose]?(): void;
    drop?(): void;
}

export interface PollableConstructor {
    new (): PollableInstance;
}

export class PragmaCallback {
    constructor(handle: number);
    call(args: Duckvalue[]): { tag: "ok", val: Duckvalue | undefined } | { tag: "err", val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class PragmaRegistry {
    registerCall(name: string, arguments: Funcarg[], returns: Logicaltype, callback: PragmaCallback, options: Extopts | undefined): { tag: "ok", val: number } | { tag: "err", val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class PreparedStatement {
    execute(params: Duckvalue[]): { tag: "ok", val: QueryResult } | { tag: "err", val: Duckerror };
    parameterCount(): number;
    drop(): void;
    [Symbol.dispose](): void;
}

export class ResultStream {
    close(): void;
    next(maxRows: number): { tag: "ok", val: Row[] | undefined } | { tag: "err", val: Duckerror };
    schema(): Columndef[];
    drop(): void;
    [Symbol.dispose](): void;
}

export class ScalarCallback {
    constructor(handle: number);
    call(args: Duckvalue[], ctx: Invokeinfo): { tag: "ok", val: Duckvalue } | { tag: "err", val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class ScalarRegistry {
    register(name: string, arguments: Funcarg[], returns: Logicaltype, callback: ScalarCallback, options: Funcopts | undefined): { tag: "ok", val: number } | { tag: "err", val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class TableCallback {
    constructor(handle: number);
    call(args: Duckvalue[]): { tag: "ok", val: Resultset } | { tag: "err", val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class TableRegistry {
    register(name: string, arguments: Funcarg[], columns: Columndef[], callback: TableCallback, options: Extopts | undefined): { tag: "ok", val: number } | { tag: "err", val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export interface DuckdbComponentExtensionLoaderHooks {
    getPendingRegistrations: () => PendingRegistrations;
}

export interface DuckdbComponentHostExtensionLoader {
    requestLoad: (name: string) => boolean;
}

export interface DuckdbExtensionCallbackDispatch {
    callScalarBatchCol: (handle: number, args: Colvec[], ctx: Invokeinfo) => { tag: "ok", val: Colvec } | { tag: "err", val: Duckerror };
    callAggregateCol: (handle: number, args: Colvec[]) => { tag: "ok", val: Duckvalue } | { tag: "err", val: Duckerror };
    callCastCol: (handle: number, arg: Colvec) => { tag: "ok", val: Colvec } | { tag: "err", val: Duckerror };
    callScalar: (handle: number, args: Duckvalue[], ctx: Invokeinfo) => { tag: "ok", val: Duckvalue } | { tag: "err", val: Duckerror };
    callTable: (handle: number, args: Duckvalue[]) => { tag: "ok", val: Resultset } | { tag: "err", val: Duckerror };
    callPragma: (handle: number, args: Duckvalue[]) => { tag: "ok", val: Duckvalue | undefined } | { tag: "err", val: Duckerror };
    callCast: (handle: number, value: Duckvalue) => { tag: "ok", val: Duckvalue } | { tag: "err", val: Duckerror };
}

export interface DuckdbExtensionColumnTypes {
}

export interface DuckdbExtensionTypes {
}

export interface TvmMemoryBytes {
    read: (ptr: Handle, len: number) => { tag: "ok", val: number[] } | { tag: "err", val: TvmError };
    write: (ptr: Handle, data: number[]) => { tag: "ok" } | { tag: "err", val: TvmError };
}

export interface TvmMemoryManager {
    createRegion: (kind: RegionKind, capacity: number) => { tag: "ok", val: number } | { tag: "err", val: TvmError };
    destroyRegion: (regionId: number) => { tag: "ok" } | { tag: "err", val: TvmError };
    alloc: (regionId: number, size: number) => { tag: "ok", val: Handle } | { tag: "err", val: TvmError };
    dealloc: (ptr: Handle) => { tag: "ok" } | { tag: "err", val: TvmError };
    describeRegion: (regionId: number) => { tag: "ok", val: RegionInfo } | { tag: "err", val: TvmError };
}

export interface TvmMemoryTypes {
}

export interface WasiCliEnvironment {
    getEnvironment: () => [string, string][];
    getArguments: () => string[];
    initialCwd: () => string | undefined;
}

export interface WasiCliStderr {
    getStderr: () => OutputStream;
}

export interface WasiCliStdout {
    getStdout: () => OutputStream;
}

export interface WasiClocksWallClock {
    now: () => Datetime;
    resolution: () => Datetime;
}

export interface WasiFilesystemPreopens {
    getDirectories: () => [Descriptor, string][];
}

export interface WasiFilesystemTypes {
    Descriptor: DescriptorConstructor;
    DirectoryEntryStream: DirectoryEntryStreamConstructor;
    filesystemErrorCode: (err: Error) => ErrorCode | undefined;
}

export interface WasiIoError {
    Error: ErrorConstructor;
}

export interface WasiIoPoll {
    Pollable: PollableConstructor;
    poll: (in_: PollableInstance[]) => number[];
}

export interface WasiIoStreams {
    InputStream: InputStreamConstructor;
    OutputStream: OutputStreamConstructor;
}

export interface DuckdbComponentDatabase {
    Connection: typeof Connection;
    ResultStream: typeof ResultStream;
    PreparedStatement: typeof PreparedStatement;
    Appender: typeof Appender;
    open: (path: string | undefined) => { tag: "ok", val: Connection } | { tag: "err", val: string };
    openWithConfig: (path: string | undefined, options: [string, string][]) => { tag: "ok", val: Connection } | { tag: "err", val: string };
    close: (conn: Connection) => void;
    interrupt: (conn: Connection) => void;
    execute: (conn: Connection, sql: string) => { tag: "ok", val: QueryResult } | { tag: "err", val: Duckerror };
    openStream: (conn: Connection, sql: string) => { tag: "ok", val: ResultStream } | { tag: "err", val: Duckerror };
    prepare: (conn: Connection, sql: string) => { tag: "ok", val: PreparedStatement } | { tag: "err", val: Duckerror };
    queryArrow: (conn: Connection, sql: string) => { tag: "ok", val: number[] } | { tag: "err", val: Duckerror };
    createAppender: (conn: Connection, schema: string | undefined, table: string) => { tag: "ok", val: Appender } | { tag: "err", val: Duckerror };
    registerExtension: (name: string, requires: Capabilitykind[]) => { tag: "ok", val: boolean } | { tag: "err", val: string };
    listRegisteredExtensions: () => ExtensionInfo[];
    handleUiRequest: (method: string, path: string, headers: string, body: number[]) => UiResponse | undefined;
    handleQuackRequest: (body: number[]) => number[] | undefined;
    registerTableFunction: (conn: Connection, name: string, columns: ColumnDescriptor[], callbackHandle: number) => { tag: "ok" } | { tag: "err", val: string };
}

export interface DuckdbExtensionConfig {
    providerVersion: () => string;
    listKeys: (prefix: string | undefined) => string[];
    getString: (path: string) => { tag: "ok", val: string | undefined } | { tag: "err", val: Configerror };
    getBool: (path: string) => { tag: "ok", val: boolean | undefined } | { tag: "err", val: Configerror };
    getI64: (path: string) => { tag: "ok", val: bigint | undefined } | { tag: "err", val: Configerror };
    getU64: (path: string) => { tag: "ok", val: bigint | undefined } | { tag: "err", val: Configerror };
    getF64: (path: string) => { tag: "ok", val: number | undefined } | { tag: "err", val: Configerror };
    getBytes: (path: string) => { tag: "ok", val: number[] | undefined } | { tag: "err", val: Configerror };
    getStringList: (path: string) => { tag: "ok", val: string[] | undefined } | { tag: "err", val: Configerror };
}

export interface DuckdbExtensionLogging {
    log: (level: Loglevel, message: string, target: string | undefined) => void;
    logFields: (level: Loglevel, message: string, fields: Logfield[]) => void;
}

export interface DuckdbExtensionRuntime {
    ScalarCallback: typeof ScalarCallback;
    TableCallback: typeof TableCallback;
    AggregateCallback: typeof AggregateCallback;
    PragmaCallback: typeof PragmaCallback;
    CastCallback: typeof CastCallback;
    ScalarRegistry: typeof ScalarRegistry;
    TableRegistry: typeof TableRegistry;
    AggregateRegistry: typeof AggregateRegistry;
    PragmaRegistry: typeof PragmaRegistry;
    MacroRegistry: typeof MacroRegistry;
    getCapability: (kind: Capabilitykind) => Capability | undefined;
    listCapabilities: () => Capabilitykind[];
}

export interface Imports {
    "duckdb:component/extension-loader-hooks": DuckdbComponentExtensionLoaderHooks;
    "duckdb:component/host-extension-loader": DuckdbComponentHostExtensionLoader;
    "duckdb:extension/callback-dispatch@5.0.0": DuckdbExtensionCallbackDispatch;
    "duckdb:extension/column-types@5.0.0": DuckdbExtensionColumnTypes;
    "duckdb:extension/types@5.0.0": DuckdbExtensionTypes;
    "tvm:memory/bytes@0.1.0": TvmMemoryBytes;
    "tvm:memory/manager@0.1.0": TvmMemoryManager;
    "tvm:memory/types@0.1.0": TvmMemoryTypes;
    "wasi:cli/environment@0.2.6": WasiCliEnvironment;
    "wasi:cli/stderr@0.2.6": WasiCliStderr;
    "wasi:cli/stdout@0.2.6": WasiCliStdout;
    "wasi:clocks/wall-clock@0.2.6": WasiClocksWallClock;
    "wasi:filesystem/preopens@0.2.6": WasiFilesystemPreopens;
    "wasi:filesystem/types@0.2.6": WasiFilesystemTypes;
    "wasi:io/error@0.2.6": WasiIoError;
    "wasi:io/poll@0.2.6": WasiIoPoll;
    "wasi:io/streams@0.2.6": WasiIoStreams;
}

export interface Exports {
    "duckdb:component/database": DuckdbComponentDatabase;
    "duckdb:extension/config@5.0.0": DuckdbExtensionConfig;
    "duckdb:extension/logging@5.0.0": DuckdbExtensionLogging;
    "duckdb:extension/runtime@5.0.0": DuckdbExtensionRuntime;
}

export function instantiate(module: WebAssembly.Module | Promise<WebAssembly.Module>, imports?: Imports): Promise<Exports>;
