/* Minimal pg_config_paths.h for the wasi libpq build (normally generated by
   postgres's Makefile). Install paths are irrelevant for TCP connections on
   wasi (no filesystem service/cert files); placeholders keep libpq compiling. */
#define PGBINDIR "/pg/bin"
#define PGSHAREDIR "/pg/share"
#define SYSCONFDIR "/pg/etc"
#define INCLUDEDIR "/pg/include"
#define PKGINCLUDEDIR "/pg/include"
#define INCLUDEDIRSERVER "/pg/include/server"
#define LIBDIR "/pg/lib"
#define PKGLIBDIR "/pg/lib"
#define LOCALEDIR "/pg/share/locale"
#define DOCDIR "/pg/share/doc"
#define HTMLDIR "/pg/share/doc"
#define MANDIR "/pg/share/man"
