//! Markdown rendering as DuckDB scalar functions (via the `pulldown-cmark` crate):
//!
//!   md_to_html(text) -> VARCHAR  render CommonMark (+ tables/strikethrough) to HTML
//!   md_to_text(text) -> VARCHAR  strip markup to plain text
//!
//! NULL in -> NULL out.

use std::collections::HashMap;
use std::sync::{
    atomic::{AtomicU32, Ordering},
    Mutex, OnceLock,
};

use wit_bindgen::rt::string::String;
use wit_bindgen::rt::vec::Vec;

wit_bindgen::generate!({
    path: "./wit",
    world: "duckdb:extension/duckdb-extension",
});

use duckdb::extension::{runtime, types};
use exports::duckdb::extension::{callback_dispatch, guest};

use pulldown_cmark::{html, Event, Options, Parser, TagEnd};

struct Extension;

impl guest::Guest for Extension {
    fn load() -> Result<types::Loadresult, types::Duckerror> {
        register_scalars()?;
        Ok(types::Loadresult {
            name: "markdown".into(),
            version: Some(env!("CARGO_PKG_VERSION").into()),
            requires: Vec::new().into(),
        })
    }
    fn reconfigure(_keys: Vec<String>) -> Result<bool, types::Duckerror> {
        Ok(false)
    }
    fn shutdown() -> Result<bool, types::Duckerror> {
        Ok(false)
    }
}

fn opts() -> Options {
    let mut o = Options::empty();
    o.insert(Options::ENABLE_TABLES);
    o.insert(Options::ENABLE_STRIKETHROUGH);
    o.insert(Options::ENABLE_FOOTNOTES);
    o
}

fn to_html(md: &str) -> std::string::String {
    let mut out = std::string::String::new();
    html::push_html(&mut out, Parser::new_ext(md, opts()));
    out
}

fn to_text(md: &str) -> std::string::String {
    let mut out = std::string::String::new();
    for ev in Parser::new_ext(md, opts()) {
        match ev {
            Event::Text(t) | Event::Code(t) => out.push_str(&t),
            Event::SoftBreak => out.push(' '),
            Event::HardBreak => out.push('\n'),
            Event::End(TagEnd::Paragraph | TagEnd::Heading(_) | TagEnd::Item) => out.push('\n'),
            _ => {}
        }
    }
    out.trim().to_string()
}

fn arg_text(args: &[types::Duckvalue], i: usize, fname: &str) -> Result<Option<String>, types::Duckerror> {
    match args.get(i) {
        Some(types::Duckvalue::Text(s)) => Ok(Some(s.clone())),
        Some(types::Duckvalue::Null) => Ok(None),
        _ => Err(types::Duckerror::Invalidargument(format!(
            "{fname}: expected VARCHAR arg at position {i}"
        ))),
    }
}

// Per-row scalar logic, UNCHANGED from the major-3 hand-written impl.
// major-4: the columnar dispatch is generated by `columnar_bridge!`, which
// bridges `colvec` <-> row and delegates to this free fn per row.
fn scalar(
    handle: u32,
    args: Vec<types::Duckvalue>,
    _ctx: types::Invokeinfo,
) -> Result<types::Duckvalue, types::Duckerror> {
    let which = scalar_handlers()
        .lock()
        .expect("scalar handler mutex poisoned")
        .get(&handle)
        .copied()
        .ok_or_else(|| types::Duckerror::Internal("unknown scalar handle".into()))?;
    let md = match arg_text(&args, 0, "markdown")? {
        Some(s) => s,
        None => return Ok(types::Duckvalue::Null),
    };
    Ok(types::Duckvalue::Text(match which {
        ScalarHandler::Html => to_html(&md),
        ScalarHandler::Text => to_text(&md),
    }))
}

datalink_extcore::columnar_bridge! {
    types = duckdb::extension::types;
    column_types = duckdb::extension::column_types;
    callback_dispatch = exports::duckdb::extension::callback_dispatch;
    target = Extension;
    scalar = scalar;
}

export!(Extension);

fn register_scalars() -> Result<(), types::Duckerror> {
    let capability = runtime::get_capability(types::Capabilitykind::Scalar)
        .ok_or_else(|| types::Duckerror::Internal("host did not expose scalar capability".into()))?;
    let registry = match capability {
        runtime::Capability::Scalar(registry) => registry,
        _ => return Err(types::Duckerror::Internal("scalar capability returned unexpected variant".into())),
    };
    let det = types::Funcflags::DETERMINISTIC | types::Funcflags::STATELESS;
    register_one(&registry, "md_to_html", det, ScalarHandler::Html)?;
    register_one(&registry, "md_to_text", det, ScalarHandler::Text)?;
    Ok(())
}

fn register_one(
    registry: &runtime::ScalarRegistry,
    name: &str,
    attributes: types::Funcflags,
    handler: ScalarHandler,
) -> Result<(), types::Duckerror> {
    let handle = NEXT_SCALAR_HANDLE.fetch_add(1, Ordering::Relaxed);
    scalar_handlers().lock().expect("scalar handler mutex poisoned").insert(handle, handler);
    let callback = runtime::ScalarCallback::new(handle);
    let args = vec![runtime::Funcarg { name: Some("value".into()), logical: types::Logicaltype::Text }];
    let opts = runtime::Funcopts {
        description: Some("Markdown rendering".into()),
        tags: vec!["markdown".into()],
        attributes,
    };
    registry.register(name, &args, &types::Logicaltype::Text, callback, Some(&opts))?;
    Ok(())
}

#[derive(Clone, Copy)]
enum ScalarHandler {
    Html,
    Text,
}

static NEXT_SCALAR_HANDLE: AtomicU32 = AtomicU32::new(1);
static SCALAR_HANDLERS: OnceLock<Mutex<HashMap<u32, ScalarHandler>>> = OnceLock::new();

fn scalar_handlers() -> &'static Mutex<HashMap<u32, ScalarHandler>> {
    SCALAR_HANDLERS.get_or_init(|| Mutex::new(HashMap::new()))
}
