//! Pin-test probe B (PLAN-prefixes v1.1 verification). Registers the SAME bare
//! scalar `pin_probe() -> INTEGER` as probe A, but returns the CONSTANT 222,
//! under a DIFFERENT prefix/expansion. Loading B after A makes bare pin_probe()
//! resolve to 222 (last-loaded wins); `.prefix prefer pin_probe pintest_a`
//! flips it to 111; `.prefix unprefer pin_probe` reverts to 222.
//! major-4: the columnar dispatch (call-scalar-batch-col / -aggregate-col /
//! -cast-col) is generated by `datalink_extcore::columnar_bridge!`, which bridges
//! `colvec` <-> row and delegates to the unchanged per-row `scalar` fn below.
use wit_bindgen::rt::string::String;
use wit_bindgen::rt::vec::Vec;
wit_bindgen::generate!({ path: "./wit", world: "duckdb:extension/duckdb-extension" });
use duckdb::extension::{runtime, types};
use exports::duckdb::extension::guest;
struct Extension;
impl guest::Guest for Extension {
    fn load() -> Result<types::Loadresult, types::Duckerror> {
        register_scalars()?;
        Ok(types::Loadresult { name: "pintest_b".into(), version: Some(env!("CARGO_PKG_VERSION").into()), requires: Vec::new().into() })
    }
    fn reconfigure(_k: Vec<String>) -> Result<bool, types::Duckerror> { Ok(false) }
    fn shutdown() -> Result<bool, types::Duckerror> { Ok(false) }
}
// Per-row scalar logic, UNCHANGED from the major-3 hand-written impl.
fn scalar(_handle: u32, _args: Vec<types::Duckvalue>, _c: types::Invokeinfo) -> Result<types::Duckvalue, types::Duckerror> {
    Ok(types::Duckvalue::Int32(222))
}
datalink_extcore::columnar_bridge! {
    types = duckdb::extension::types;
    column_types = duckdb::extension::column_types;
    callback_dispatch = exports::duckdb::extension::callback_dispatch;
    target = Extension;
    scalar = scalar;
}
export!(Extension);
fn register_scalars() -> Result<(), types::Duckerror> {
    let cap = runtime::get_capability(types::Capabilitykind::Scalar).ok_or_else(|| types::Duckerror::Internal("no scalar capability".into()))?;
    let reg = match cap { runtime::Capability::Scalar(r) => r, _ => return Err(types::Duckerror::Internal("bad capability".into())) };
    let det = types::Funcflags::DETERMINISTIC | types::Funcflags::STATELESS;
    reg.register("pin_probe", &[], &types::Logicaltype::Int32, runtime::ScalarCallback::new(1),
        Some(&runtime::Funcopts { description: Some("pin-test probe B -> 222".into()), tags: vec!["test".into()], attributes: det }))?;
    Ok(())
}
