//! Natural-language detection as DuckDB scalars (via `whatlang`):
//!   detect_language(text) -> ISO 639-3 code, detect_language_name(text) ->
//!   English name, detect_script(text) -> script name. NULL / undetectable -> NULL.
//!
//! major-4: the columnar dispatch (call-scalar-batch-col / -aggregate-col /
//! -cast-col) is generated by `datalink_extcore::columnar_bridge!`, which bridges
//! `colvec` <-> row and delegates to the unchanged per-row `scalar` fn below.
use std::collections::HashMap;
use std::sync::{atomic::{AtomicU32, Ordering}, Mutex, OnceLock};
use wit_bindgen::rt::string::String;
use wit_bindgen::rt::vec::Vec;
wit_bindgen::generate!({ path: "./wit", world: "duckdb:extension/duckdb-extension" });
use duckdb::extension::{runtime, types};
use exports::duckdb::extension::guest;
struct Extension;
impl guest::Guest for Extension {
    fn load() -> Result<types::Loadresult, types::Duckerror> {
        register_scalars()?;
        Ok(types::Loadresult { name: "whatlang".into(), version: Some(env!("CARGO_PKG_VERSION").into()), requires: Vec::new().into() })
    }
    fn reconfigure(_k: Vec<String>) -> Result<bool, types::Duckerror> { Ok(false) }
    fn shutdown() -> Result<bool, types::Duckerror> { Ok(false) }
}
fn arg(args: &[types::Duckvalue], i: usize) -> Option<String> {
    match args.get(i) { Some(types::Duckvalue::Text(s)) => Some(s.clone()), _ => None }
}
// Per-row scalar logic, UNCHANGED from the major-3 hand-written impl.
fn scalar(handle: u32, args: Vec<types::Duckvalue>, _c: types::Invokeinfo) -> Result<types::Duckvalue, types::Duckerror> {
    let which = handlers().lock().unwrap().get(&handle).copied()
        .ok_or_else(|| types::Duckerror::Internal("unknown scalar handle".into()))?;
    let info = match arg(&args, 0).and_then(|s| whatlang::detect(&s)) { Some(i) => i, None => return Ok(types::Duckvalue::Null) };
    Ok(types::Duckvalue::Text(match which {
        W::Code => info.lang().code().into(),
        W::Name => info.lang().eng_name().into(),
        W::Script => info.script().to_string().into(),
    }))
}
datalink_extcore::columnar_bridge! {
    types = duckdb::extension::types;
    column_types = duckdb::extension::column_types;
    callback_dispatch = exports::duckdb::extension::callback_dispatch;
    target = Extension;
    scalar = scalar;
}
export!(Extension);
fn register_scalars() -> Result<(), types::Duckerror> {
    let cap = runtime::get_capability(types::Capabilitykind::Scalar).ok_or_else(|| types::Duckerror::Internal("no scalar capability".into()))?;
    let reg = match cap { runtime::Capability::Scalar(r) => r, _ => return Err(types::Duckerror::Internal("bad capability".into())) };
    let det = types::Funcflags::DETERMINISTIC | types::Funcflags::STATELESS;
    one(&reg, "detect_language", det, W::Code)?;
    one(&reg, "detect_language_name", det, W::Name)?;
    one(&reg, "detect_script", det, W::Script)?;
    Ok(())
}
fn one(reg: &runtime::ScalarRegistry, name: &str, attr: types::Funcflags, w: W) -> Result<(), types::Duckerror> {
    let h = NEXT.fetch_add(1, Ordering::Relaxed); handlers().lock().unwrap().insert(h, w);
    reg.register(name, &[runtime::Funcarg { name: Some("text".into()), logical: types::Logicaltype::Text }],
        &types::Logicaltype::Text, runtime::ScalarCallback::new(h),
        Some(&runtime::Funcopts { description: Some("language detection".into()), tags: vec!["nlp".into()], attributes: attr }))?;
    Ok(())
}
#[derive(Clone, Copy)] enum W { Code, Name, Script }
static NEXT: AtomicU32 = AtomicU32::new(1);
static HANDLERS: OnceLock<Mutex<HashMap<u32, W>>> = OnceLock::new();
fn handlers() -> &'static Mutex<HashMap<u32, W>> { HANDLERS.get_or_init(|| Mutex::new(HashMap::new())) }
