//! Compile PRQL to SQL as DuckDB scalars (via `prqlc`):
//!   prql_to_sql(prql) -> text   (compile PRQL to SQL; NULL on compile error),
//!   prql_is_valid(prql) -> boolean.
//!   NULL input -> NULL. Never panics.
use std::collections::HashMap;
use std::sync::{atomic::{AtomicU32, Ordering}, Mutex, OnceLock};
use wit_bindgen::rt::string::String;
use wit_bindgen::rt::vec::Vec;
wit_bindgen::generate!({ path: "./wit", world: "duckdb:extension/duckdb-extension" });
use duckdb::extension::{runtime, types};
use exports::duckdb::extension::guest;

struct Extension;

impl guest::Guest for Extension {
    fn load() -> Result<types::Loadresult, types::Duckerror> {
        register_scalars()?;
        Ok(types::Loadresult { name: "prql".into(), version: Some(env!("CARGO_PKG_VERSION").into()), requires: Vec::new().into() })
    }
    fn reconfigure(_k: Vec<String>) -> Result<bool, types::Duckerror> { Ok(false) }
    fn shutdown() -> Result<bool, types::Duckerror> { Ok(false) }
}

fn text_arg(args: &[types::Duckvalue], i: usize) -> Option<String> {
    match args.get(i) { Some(types::Duckvalue::Text(s)) => Some(s.clone()), _ => None }
}

/// Compile a PRQL string to SQL, targeting the DuckDB dialect. Returns None on
/// any compile error. Catches panics defensively so a compiler bug can't unwind
/// across the WIT boundary.
fn compile(src: &str) -> Option<std::string::String> {
    let opts = prqlc::Options::default()
        .no_signature()
        .with_target(prqlc::Target::Sql(Some(prqlc::sql::Dialect::DuckDb)));
    let res = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        prqlc::compile(src, &opts)
    }));
    match res {
        Ok(Ok(sql)) => Some(sql),
        _ => None,
    }
}

// Per-row scalar logic, UNCHANGED from the major-3 hand-written impl.
fn scalar(handle: u32, args: Vec<types::Duckvalue>, _c: types::Invokeinfo) -> Result<types::Duckvalue, types::Duckerror> {
    let which = handlers().lock().unwrap().get(&handle).copied()
        .ok_or_else(|| types::Duckerror::Internal("unknown scalar handle".into()))?;
    // NULL input -> NULL.
    let src = match text_arg(&args, 0) {
        Some(s) => s,
        None => return Ok(types::Duckvalue::Null),
    };
    Ok(match which {
        P::ToSql => match compile(&src) {
            Some(sql) => types::Duckvalue::Text(sql.into()),
            None => types::Duckvalue::Null,
        },
        P::IsValid => types::Duckvalue::Boolean(compile(&src).is_some()),
    })
}
// major-4: the columnar dispatch (call-scalar-batch-col / -aggregate-col /
// -cast-col) is generated by `columnar_bridge!`, which bridges colvec <-> row
// and delegates to the unchanged per-row `scalar` fn above.
datalink_extcore::columnar_bridge! {
    types = duckdb::extension::types;
    column_types = duckdb::extension::column_types;
    callback_dispatch = exports::duckdb::extension::callback_dispatch;
    target = Extension;
    scalar = scalar;
}
export!(Extension);

fn register_scalars() -> Result<(), types::Duckerror> {
    let cap = runtime::get_capability(types::Capabilitykind::Scalar).ok_or_else(|| types::Duckerror::Internal("no scalar capability".into()))?;
    let reg = match cap { runtime::Capability::Scalar(r) => r, _ => return Err(types::Duckerror::Internal("bad capability".into())) };
    let det = types::Funcflags::DETERMINISTIC | types::Funcflags::STATELESS;

    let h = NEXT.fetch_add(1, Ordering::Relaxed); handlers().lock().unwrap().insert(h, P::ToSql);
    reg.register("prql_to_sql",
        &[runtime::Funcarg { name: Some("prql".into()), logical: types::Logicaltype::Text }],
        &types::Logicaltype::Text, runtime::ScalarCallback::new(h),
        Some(&runtime::Funcopts { description: Some("compile PRQL to SQL (DuckDB dialect); NULL on error".into()), tags: vec!["prql".into()], attributes: det }))?;

    let h = NEXT.fetch_add(1, Ordering::Relaxed); handlers().lock().unwrap().insert(h, P::IsValid);
    reg.register("prql_is_valid",
        &[runtime::Funcarg { name: Some("prql".into()), logical: types::Logicaltype::Text }],
        &types::Logicaltype::Boolean, runtime::ScalarCallback::new(h),
        Some(&runtime::Funcopts { description: Some("true if the PRQL compiles".into()), tags: vec!["prql".into()], attributes: det }))?;
    Ok(())
}

#[derive(Clone, Copy, PartialEq)] enum P { ToSql, IsValid }
static NEXT: AtomicU32 = AtomicU32::new(1);
static HANDLERS: OnceLock<Mutex<HashMap<u32, P>>> = OnceLock::new();
fn handlers() -> &'static Mutex<HashMap<u32, P>> { HANDLERS.get_or_init(|| Mutex::new(HashMap::new())) }
