-- dbf extension smoke: read_dbf(data BLOB) -> melted (record_no, field, value).
--
-- Fixture: a 1-record dBASE III file with two Character fields, generated by the
-- `dbase` crate's TableWriterBuilder (see README / fixture note in smoke.expected):
--   NAME = 'Alice', AGE = '30'
-- Melted => (1,'NAME','Alice'), (1,'AGE','30').
SELECT record_no, field, value
FROM read_dbf(unhex('037E061801000000610018000000000000000000000000000000000000F000004E414D450000000000000043000000001400000000000000000000000000000041474500000000000000004300000000030000000000000000000000000000000D20416C6963652020202020202020202020202020203330201A'))
ORDER BY record_no, field;

-- Malformed blob -> zero rows (proves the function is wired, never panics).
SELECT count(*) AS bad_rows FROM read_dbf('not a dbf'::BLOB);

-- Empty blob -> zero rows.
SELECT count(*) AS empty_rows FROM read_dbf(''::BLOB);
