// Generated by wit-js-bindgen 0.0.1 — do not edit.
// world: root
// role: runtime-guest (byte-frame codec)

// Driver contract expected from the caller.
// Subset of `RuntimeGuestDriver` from @tegmentum/wasmos-browser.
export interface RuntimeGuestDriver {
    parseComponent(bytes: Uint8Array): number;
    registerHostProvider(interfaceName: string, funcCount: number): number;
    registerRouter(providerHandle: number, callback: (funcIdx: number, args: Uint8Array) => Uint8Array): void;
    instantiateWithImports(componentHandle: number, imports: ReadonlyArray<{ interfaceName: string; providerHandle: number }>): number;
    callExport(instanceHandle: number, exportName: string, argFrame: Uint8Array): Uint8Array;
}

export interface Decimalshape {
    width: number;
    scale: number;
}

export type Logicaltype = { tag: "boolean" } | { tag: "int64" } | { tag: "uint64" } | { tag: "float64" } | { tag: "text" } | { tag: "blob" } | { tag: "int32" } | { tag: "timestamp" } | { tag: "int8" } | { tag: "int16" } | { tag: "uint8" } | { tag: "uint16" } | { tag: "uint32" } | { tag: "float32" } | { tag: "date" } | { tag: "time" } | { tag: "timestamptz" } | { tag: "decimal"; val: Decimalshape } | { tag: "interval" } | { tag: "uuid" } | { tag: "hugeint" } | { tag: "uhugeint" } | { tag: "complex"; val: string };

export interface Funcarg {
    name: string | undefined;
    logical: Logicaltype;
}

export interface Funcflags {
    deterministic: boolean;
    commutative: boolean;
    stateless: boolean;
    sideeffecting: boolean;
    deprecated: boolean;
}

export interface Funcopts {
    description: string | undefined;
    tags: string[];
    attributes: Funcflags;
}

export type Duckerror = { tag: "invalidargument"; val: string } | { tag: "unsupported"; val: string } | { tag: "invalidstate"; val: string } | { tag: "io"; val: string } | { tag: "internal"; val: string };

export interface Columndef {
    name: string;
    logical: Logicaltype;
}

export interface Extopts {
    description: string | undefined;
    tags: string[];
}

export type Capabilitykind = "scalar" | "table" | "aggregate" | "pragma" | "macro" | "catalog" | "file-format";

export interface Loadresult {
    name: string;
    version: string | undefined;
    requires: Capabilitykind[];
}

export interface Decimalvalue {
    lower: bigint;
    upper: bigint;
    width: number;
    scale: number;
}

export interface Intervalvalue {
    months: number;
    days: number;
    micros: bigint;
}

export interface Uuidvalue {
    hi: bigint;
    lo: bigint;
}

export interface Hugeintvalue {
    lower: bigint;
    upper: bigint;
}

export interface Uhugeintvalue {
    lower: bigint;
    upper: bigint;
}

export interface Complexvalue {
    typeExpr: string;
    json: string;
}

export type Duckvalue = { tag: "null" } | { tag: "boolean"; val: boolean } | { tag: "int64"; val: bigint } | { tag: "uint64"; val: bigint } | { tag: "float64"; val: number } | { tag: "text"; val: string } | { tag: "blob"; val: number[] } | { tag: "int32"; val: number } | { tag: "timestamp"; val: bigint } | { tag: "int8"; val: number } | { tag: "int16"; val: number } | { tag: "uint8"; val: number } | { tag: "uint16"; val: number } | { tag: "uint32"; val: number } | { tag: "float32"; val: number } | { tag: "date"; val: number } | { tag: "time"; val: bigint } | { tag: "timestamptz"; val: bigint } | { tag: "decimal"; val: Decimalvalue } | { tag: "interval"; val: Intervalvalue } | { tag: "uuid"; val: Uuidvalue } | { tag: "hugeint"; val: Hugeintvalue } | { tag: "uhugeint"; val: Uhugeintvalue } | { tag: "complex"; val: Complexvalue };

export interface Invokeinfo {
    rowindex: bigint | undefined;
    iswindow: boolean;
}

export type Resultset = Duckvalue[][];

export type Capability = { tag: "scalar"; val: ScalarRegistry } | { tag: "table"; val: TableRegistry } | { tag: "aggregate"; val: AggregateRegistry } | { tag: "pragma"; val: PragmaRegistry } | { tag: "macro"; val: MacroRegistry };

export interface DuckInt128 {
    lower: bigint;
    upper: bigint;
}

export interface DuckUint128 {
    lower: bigint;
    upper: bigint;
}

export interface NestedColumn {
    encoded: number[];
}

export interface MapColumn {
    keysEncoded: number[];
    valsEncoded: number[];
}

export interface ArrayColumn {
    size: number;
    encoded: number[];
}

export type Column = { tag: "boolean"; val: boolean[] } | { tag: "int64"; val: bigint[] } | { tag: "uint64"; val: bigint[] } | { tag: "float64"; val: number[] } | { tag: "int32"; val: number[] } | { tag: "timestamp"; val: bigint[] } | { tag: "int8"; val: number[] } | { tag: "int16"; val: number[] } | { tag: "uint8"; val: number[] } | { tag: "uint16"; val: number[] } | { tag: "uint32"; val: number[] } | { tag: "float32"; val: number[] } | { tag: "date"; val: number[] } | { tag: "time"; val: bigint[] } | { tag: "timestamptz"; val: bigint[] } | { tag: "decimal"; val: Decimalvalue[] } | { tag: "interval"; val: Intervalvalue[] } | { tag: "uuid"; val: Uuidvalue[] } | { tag: "text"; val: string[] } | { tag: "blob"; val: number[][] } | { tag: "hugeint"; val: DuckInt128[] } | { tag: "uhugeint"; val: DuckUint128[] } | { tag: "list-col"; val: NestedColumn } | { tag: "struct-col"; val: NestedColumn } | { tag: "map-col"; val: MapColumn } | { tag: "array-col"; val: ArrayColumn } | { tag: "complex"; val: Complexvalue[] };

export interface Colvec {
    data: Column;
    validity: number[];
    rows: number;
}

export type Duration = bigint;

export type StreamError = { tag: "last-operation-failed"; val: unknown } | { tag: "closed" };

export class AggregateRegistry {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    drop(): void;
    [Symbol.dispose](): void;
}

export class Error {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    drop(): void;
    [Symbol.dispose](): void;
}

export class InputStream {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    drop(): void;
    [Symbol.dispose](): void;
}

export class MacroRegistry {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    drop(): void;
    [Symbol.dispose](): void;
}

export class OutputStream {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    blockingFlush(): { tag: "ok" } | { tag: "err"; val: StreamError };
    checkWrite(): { tag: "ok"; val: bigint } | { tag: "err"; val: StreamError };
    subscribe(): Pollable;
    write(contents: number[]): { tag: "ok" } | { tag: "err"; val: StreamError };
    drop(): void;
    [Symbol.dispose](): void;
}

export class Pollable {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    block(): void;
    drop(): void;
    [Symbol.dispose](): void;
}

export class PragmaRegistry {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    drop(): void;
    [Symbol.dispose](): void;
}

export class ScalarCallback {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    static attach(driver: RuntimeGuestDriver, instanceHandle: number, handle: number): ScalarCallback;
    drop(): void;
    [Symbol.dispose](): void;
}

export class ScalarRegistry {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    register(name: string, arguments_: Funcarg[], returns: Logicaltype, callback: ScalarCallback, options: Funcopts | undefined): { tag: "ok"; val: number } | { tag: "err"; val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class TableCallback {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    static attach(driver: RuntimeGuestDriver, instanceHandle: number, handle: number): TableCallback;
    drop(): void;
    [Symbol.dispose](): void;
}

export class TableRegistry {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    register(name: string, arguments_: Funcarg[], columns: Columndef[], callback: TableCallback, options: Extopts | undefined): { tag: "ok"; val: number } | { tag: "err"; val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class TerminalInput {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    drop(): void;
    [Symbol.dispose](): void;
}

export class TerminalOutput {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    drop(): void;
    [Symbol.dispose](): void;
}

export interface RootExports {
    "duckdb:extension/callback-dispatch@5.0.0": {
        callScalarBatchCol(handle: number, args: Colvec[], ctx: Invokeinfo): { tag: "ok"; val: Colvec } | { tag: "err"; val: Duckerror };
        callAggregateCol(handle: number, args: Colvec[]): { tag: "ok"; val: Duckvalue } | { tag: "err"; val: Duckerror };
        callCastCol(handle: number, arg: Colvec): { tag: "ok"; val: Colvec } | { tag: "err"; val: Duckerror };
        callScalar(handle: number, args: Duckvalue[], ctx: Invokeinfo): { tag: "ok"; val: Duckvalue } | { tag: "err"; val: Duckerror };
        callTable(handle: number, args: Duckvalue[]): { tag: "ok"; val: Resultset } | { tag: "err"; val: Duckerror };
        callPragma(handle: number, args: Duckvalue[]): { tag: "ok"; val: Duckvalue | undefined } | { tag: "err"; val: Duckerror };
        callCast(handle: number, value: Duckvalue): { tag: "ok"; val: Duckvalue } | { tag: "err"; val: Duckerror };
    };
    "duckdb:extension/guest@5.0.0": {
        load(): { tag: "ok"; val: Loadresult } | { tag: "err"; val: Duckerror };
        reconfigure(keys: string[]): { tag: "ok"; val: boolean } | { tag: "err"; val: Duckerror };
        shutdown(): { tag: "ok"; val: boolean } | { tag: "err"; val: Duckerror };
    };
}

export function bindRuntimeGuest(driver: RuntimeGuestDriver, instanceHandle: number): RootExports;

export interface RootImports {
    "duckdb:extension/runtime@5.0.0"?: {
        "[constructor]scalar-callback"(handle: number): number;
        "[constructor]table-callback"(handle: number): number;
        "[method]scalar-registry.register"(self: number, name: string, arguments_: Funcarg[], returns: Logicaltype, callback: number, options: Funcopts | undefined): { tag: "ok"; val: number } | { tag: "err"; val: Duckerror };
        "[method]table-registry.register"(self: number, name: string, arguments_: Funcarg[], columns: Columndef[], callback: number, options: Extopts | undefined): { tag: "ok"; val: number } | { tag: "err"; val: Duckerror };
        "getCapability"(kind: Capabilitykind): Capability | undefined;
    };
    "wasi:cli/environment@0.2.9"?: {
        "getEnvironment"(): [string, string][];
    };
    "wasi:cli/exit@0.2.9"?: {
        "exit"(status: { tag: "ok" } | { tag: "err" }): void;
    };
    "wasi:cli/stderr@0.2.9"?: {
        "getStderr"(): number;
    };
    "wasi:cli/stdin@0.2.9"?: {
        "getStdin"(): number;
    };
    "wasi:cli/stdout@0.2.9"?: {
        "getStdout"(): number;
    };
    "wasi:cli/terminal-stderr@0.2.9"?: {
        "getTerminalStderr"(): number | undefined;
    };
    "wasi:cli/terminal-stdin@0.2.9"?: {
        "getTerminalStdin"(): number | undefined;
    };
    "wasi:cli/terminal-stdout@0.2.9"?: {
        "getTerminalStdout"(): number | undefined;
    };
    "wasi:clocks/monotonic-clock@0.2.9"?: {
        "subscribeDuration"(when: bigint): number;
    };
    "wasi:io/poll@0.2.9"?: {
        "[method]pollable.block"(self: number): void;
        "poll"(in_: number[]): number[];
    };
    "wasi:io/streams@0.2.9"?: {
        "[method]output-stream.check-write"(self: number): { tag: "ok"; val: bigint } | { tag: "err"; val: StreamError };
        "[method]output-stream.write"(self: number, contents: number[]): { tag: "ok" } | { tag: "err"; val: StreamError };
        "[method]output-stream.blocking-flush"(self: number): { tag: "ok" } | { tag: "err"; val: StreamError };
        "[method]output-stream.subscribe"(self: number): number;
    };
    "wasi:random/insecure-seed@0.2.9"?: {
        "insecureSeed"(): [bigint, bigint];
    };
}

export function registerHostProviders(driver: RuntimeGuestDriver, impls?: RootImports): Record<string, number>;

