// Generated by wit-js-bindgen 0.0.1 — do not edit.
// world: root
// role: runtime-guest (byte-frame codec)

// Driver contract expected from the caller.
// Subset of `RuntimeGuestDriver` from @tegmentum/wasmos-browser.
export interface RuntimeGuestDriver {
    parseComponent(bytes: Uint8Array): number;
    registerHostProvider(interfaceName: string, funcCount: number): number;
    registerRouter(providerHandle: number, callback: (funcIdx: number, args: Uint8Array) => Uint8Array): void;
    instantiateWithImports(componentHandle: number, imports: ReadonlyArray<{ interfaceName: string; providerHandle: number }>): number;
    callExport(instanceHandle: number, exportName: string, argFrame: Uint8Array): Uint8Array;
}

export type Duckerror = { tag: "invalidargument"; val: string } | { tag: "unsupported"; val: string } | { tag: "invalidstate"; val: string } | { tag: "io"; val: string } | { tag: "internal"; val: string };

export interface Decimalvalue {
    lower: bigint;
    upper: bigint;
    width: number;
    scale: number;
}

export interface Intervalvalue {
    months: number;
    days: number;
    micros: bigint;
}

export interface Uuidvalue {
    hi: bigint;
    lo: bigint;
}

export interface Complexvalue {
    typeExpr: string;
    json: string;
}

export type Duckvalue = { tag: "null" } | { tag: "boolean"; val: boolean } | { tag: "int64"; val: bigint } | { tag: "uint64"; val: bigint } | { tag: "float64"; val: number } | { tag: "text"; val: string } | { tag: "blob"; val: number[] } | { tag: "int32"; val: number } | { tag: "timestamp"; val: bigint } | { tag: "int8"; val: number } | { tag: "int16"; val: number } | { tag: "uint8"; val: number } | { tag: "uint16"; val: number } | { tag: "uint32"; val: number } | { tag: "float32"; val: number } | { tag: "date"; val: number } | { tag: "time"; val: bigint } | { tag: "timestamptz"; val: bigint } | { tag: "decimal"; val: Decimalvalue } | { tag: "interval"; val: Intervalvalue } | { tag: "uuid"; val: Uuidvalue } | { tag: "complex"; val: Complexvalue };

export type Logicaltype = { tag: "boolean" } | { tag: "int64" } | { tag: "uint64" } | { tag: "float64" } | { tag: "text" } | { tag: "blob" } | { tag: "int32" } | { tag: "timestamp" } | { tag: "int8" } | { tag: "int16" } | { tag: "uint8" } | { tag: "uint16" } | { tag: "uint32" } | { tag: "float32" } | { tag: "date" } | { tag: "time" } | { tag: "timestamptz" } | { tag: "decimal" } | { tag: "interval" } | { tag: "uuid" } | { tag: "complex"; val: string };

export interface Columndef {
    name: string;
    logical: Logicaltype;
}

export type Resultset = Duckvalue[][];

export interface Invokeinfo {
    rowindex: bigint | undefined;
    iswindow: boolean;
}

export interface Funcflags {
    deterministic: boolean;
    commutative: boolean;
    stateless: boolean;
    sideeffecting: boolean;
    deprecated: boolean;
}

export type Capabilitykind = "scalar" | "table" | "aggregate" | "pragma" | "macro" | "catalog" | "file-format";

export type Configerror = { tag: "invalidkey"; val: string } | { tag: "typemismatch"; val: string } | { tag: "unavailable"; val: string } | { tag: "internalconfig"; val: string };

export interface Logfield {
    key: string;
    value: string;
}

export type Loglevel = "trace" | "debug" | "info" | "warn" | "error";

export interface Extopts {
    description: string | undefined;
    tags: string[];
}

export interface Funcarg {
    name: string | undefined;
    logical: Logicaltype;
}

export interface Funcopts {
    description: string | undefined;
    tags: string[];
    attributes: Funcflags;
}

export type Rowbatch = Duckvalue[][];

export interface FuncArg {
    name: string | undefined;
    logical: Logicaltype;
}

export interface FuncOpts {
    description: string | undefined;
    tags: string[];
    attributes: Funcflags;
}

export interface ScalarRegistration {
    name: string;
    arguments_: FuncArg[];
    returns: Logicaltype;
    callbackHandle: number;
    options: FuncOpts | undefined;
}

export interface ExtOpts {
    description: string | undefined;
    tags: string[];
}

export interface TableRegistration {
    name: string;
    arguments_: FuncArg[];
    columns: Columndef[];
    callbackHandle: number;
    options: ExtOpts | undefined;
}

export interface AggregateRegistration {
    name: string;
    arguments_: FuncArg[];
    returns: Logicaltype;
    callbackHandle: number;
    options: FuncOpts | undefined;
}

export interface MacroRegistration {
    schema: string;
    name: string;
    parameters: string[];
    definitionSql: string;
}

export interface ReplacementScanRegistration {
    extensions: string[];
    functionName: string;
}

export interface LogicalTypeRegistration {
    name: string;
    physical: string;
}

export interface CastRegistration {
    source: string;
    target: string;
    callbackHandle: number;
}

export interface PendingRegistrations {
    scalars: ScalarRegistration[];
    tables: TableRegistration[];
    aggregates: AggregateRegistration[];
    macros: MacroRegistration[];
    replacementScans: ReplacementScanRegistration[];
    logicalTypes: LogicalTypeRegistration[];
    casts: CastRegistration[];
}

export type Column = { tag: "boolean"; val: boolean[] } | { tag: "int64"; val: bigint[] } | { tag: "uint64"; val: bigint[] } | { tag: "float64"; val: number[] } | { tag: "int32"; val: number[] } | { tag: "timestamp"; val: bigint[] } | { tag: "int8"; val: number[] } | { tag: "int16"; val: number[] } | { tag: "uint8"; val: number[] } | { tag: "uint16"; val: number[] } | { tag: "uint32"; val: number[] } | { tag: "float32"; val: number[] } | { tag: "date"; val: number[] } | { tag: "time"; val: bigint[] } | { tag: "timestamptz"; val: bigint[] } | { tag: "decimal"; val: Decimalvalue[] } | { tag: "interval"; val: Intervalvalue[] } | { tag: "uuid"; val: Uuidvalue[] } | { tag: "text"; val: string[] } | { tag: "blob"; val: number[][] } | { tag: "complex"; val: Complexvalue[] };

export interface Colvec {
    data: Column;
    validity: number[];
    rows: number;
}

export type CompareOp = "eq" | "ne" | "lt" | "le" | "gt" | "ge" | "is-null" | "is-not-null";

export interface ScanFilter {
    column: number;
    op: CompareOp;
    value: Duckvalue;
}

export interface ScanRequest {
    table: string;
    projection: number[];
    filters: ScanFilter[];
    limit: bigint | undefined;
    wantsRowid: boolean;
}

export interface IndexHit {
    rowid: bigint;
    distance: number;
}

export interface CollationSpec {
    name: string;
    transformScalar: string;
    combinable: boolean;
}

export interface PragmaSpec {
    name: string;
    callbackHandle: number;
}

export interface ParserSpec {
    name: string;
    callbackHandle: number;
}

export interface OptimizerSpec {
    ruleName: string;
    callbackHandle: number;
}

export interface FileOpenResult {
    handle: number;
    size: bigint;
}

export type TsFilterOp = "eq" | "ne" | "lt" | "le" | "gt" | "ge" | "is-in" | "is-null" | "is-not-null";

export interface TsFilter {
    column: number;
    op: TsFilterOp;
    values: Duckvalue[];
}

export interface TsOpenResult {
    cursor: number;
    columns: Columndef[];
}

export interface FilterableTable {
    name: string;
    arguments_: Columndef[];
    columns: Columndef[];
    handle: number;
}

export interface Handle {
    regionId: number;
    generation: number;
    offset: number;
}

export type TvmError = { tag: "region-not-found"; val: number } | { tag: "stale-handle" } | { tag: "out-of-bounds" } | { tag: "not-resident" } | { tag: "allocation-failed" } | { tag: "backing-store"; val: string } | { tag: "pinned" };

export type RegionKind = "hot-heap" | "object-arena" | "blob-arena" | "page-store" | "scratch" | "device-state" | "code-cache";

export type Instant = bigint;

export type Duration = bigint;

export interface Datetime {
    seconds: bigint;
    nanoseconds: number;
}

export type StreamError = { tag: "last-operation-failed"; val: unknown } | { tag: "closed" };

export type ErrorCode = "access" | "would-block" | "already" | "bad-descriptor" | "busy" | "deadlock" | "quota" | "exist" | "file-too-large" | "illegal-byte-sequence" | "in-progress" | "interrupted" | "invalid" | "io" | "is-directory" | "loop" | "too-many-links" | "message-size" | "name-too-long" | "no-device" | "no-entry" | "no-lock" | "insufficient-memory" | "insufficient-space" | "not-directory" | "not-empty" | "not-recoverable" | "unsupported" | "no-tty" | "no-such-device" | "overflow" | "not-permitted" | "pipe" | "read-only" | "invalid-seek" | "text-file-busy" | "cross-device";

export type DescriptorType = "unknown" | "block-device" | "character-device" | "directory" | "fifo" | "symbolic-link" | "regular-file" | "socket";

export interface DirectoryEntry {
    type: DescriptorType;
    name: string;
}

export type Filesize = bigint;

export type LinkCount = bigint;

export interface DescriptorStat {
    type: DescriptorType;
    linkCount: LinkCount;
    size: Filesize;
    dataAccessTimestamp: Datetime | undefined;
    dataModificationTimestamp: Datetime | undefined;
    statusChangeTimestamp: Datetime | undefined;
}

export interface PathFlags {
    symlinkFollow: boolean;
}

export interface OpenFlags {
    create: boolean;
    directory: boolean;
    exclusive: boolean;
    truncate: boolean;
}

export interface DescriptorFlags {
    read: boolean;
    write: boolean;
    fileIntegritySync: boolean;
    dataIntegritySync: boolean;
    requestedWriteSync: boolean;
    mutateDirectory: boolean;
}

export interface MetadataHashValue {
    lower: bigint;
    upper: bigint;
}

export type Row = Duckvalue[];

export interface QueryResult {
    columns: Columndef[];
    rows: Row[];
}

export interface ExtensionInfo {
    name: string;
    requires: Capabilitykind[];
}

export interface UiResponse {
    status: number;
    headers: string;
    body: number[];
}

export type Capability = { tag: "scalar"; val: ScalarRegistry } | { tag: "table"; val: TableRegistry } | { tag: "aggregate"; val: AggregateRegistry } | { tag: "pragma"; val: PragmaRegistry } | { tag: "macro"; val: MacroRegistry };

export class AggregateCallback {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    static attach(driver: RuntimeGuestDriver, instanceHandle: number, handle: number): AggregateCallback;
    call(rows: Rowbatch): { tag: "ok"; val: Duckvalue } | { tag: "err"; val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class AggregateRegistry {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    register(name: string, arguments_: Funcarg[], returns: Logicaltype, callback: AggregateCallback, options: Funcopts | undefined): { tag: "ok"; val: number } | { tag: "err"; val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class Appender {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    appendRow(values: Duckvalue[]): { tag: "ok" } | { tag: "err"; val: Duckerror };
    close(): { tag: "ok" } | { tag: "err"; val: Duckerror };
    flush(): { tag: "ok" } | { tag: "err"; val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class CastCallback {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    static attach(driver: RuntimeGuestDriver, instanceHandle: number, handle: number): CastCallback;
    call(value: Duckvalue): { tag: "ok"; val: Duckvalue } | { tag: "err"; val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class Connection {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    drop(): void;
    [Symbol.dispose](): void;
}

export class Descriptor {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    appendViaStream(): { tag: "ok"; val: OutputStream } | { tag: "err"; val: ErrorCode };
    createDirectoryAt(path: string): { tag: "ok" } | { tag: "err"; val: ErrorCode };
    getFlags(): { tag: "ok"; val: DescriptorFlags } | { tag: "err"; val: ErrorCode };
    metadataHash(): { tag: "ok"; val: MetadataHashValue } | { tag: "err"; val: ErrorCode };
    openAt(pathFlags: PathFlags, path: string, openFlags: OpenFlags, flags: DescriptorFlags): { tag: "ok"; val: Descriptor } | { tag: "err"; val: ErrorCode };
    read(length: Filesize, offset: Filesize): { tag: "ok"; val: [number[], boolean] } | { tag: "err"; val: ErrorCode };
    readDirectory(): { tag: "ok"; val: DirectoryEntryStream } | { tag: "err"; val: ErrorCode };
    readViaStream(offset: Filesize): { tag: "ok"; val: InputStream } | { tag: "err"; val: ErrorCode };
    readlinkAt(path: string): { tag: "ok"; val: string } | { tag: "err"; val: ErrorCode };
    removeDirectoryAt(path: string): { tag: "ok" } | { tag: "err"; val: ErrorCode };
    renameAt(oldPath: string, newDescriptor: Descriptor, newPath: string): { tag: "ok" } | { tag: "err"; val: ErrorCode };
    setSize(size: Filesize): { tag: "ok" } | { tag: "err"; val: ErrorCode };
    stat(): { tag: "ok"; val: DescriptorStat } | { tag: "err"; val: ErrorCode };
    statAt(pathFlags: PathFlags, path: string): { tag: "ok"; val: DescriptorStat } | { tag: "err"; val: ErrorCode };
    sync(): { tag: "ok" } | { tag: "err"; val: ErrorCode };
    syncData(): { tag: "ok" } | { tag: "err"; val: ErrorCode };
    unlinkFileAt(path: string): { tag: "ok" } | { tag: "err"; val: ErrorCode };
    write(buffer: number[], offset: Filesize): { tag: "ok"; val: Filesize } | { tag: "err"; val: ErrorCode };
    writeViaStream(offset: Filesize): { tag: "ok"; val: OutputStream } | { tag: "err"; val: ErrorCode };
    drop(): void;
    [Symbol.dispose](): void;
}

export class DirectoryEntryStream {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    readDirectoryEntry(): { tag: "ok"; val: DirectoryEntry | undefined } | { tag: "err"; val: ErrorCode };
    drop(): void;
    [Symbol.dispose](): void;
}

export class Error {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    drop(): void;
    [Symbol.dispose](): void;
}

export class InputStream {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    read(len: bigint): { tag: "ok"; val: number[] } | { tag: "err"; val: StreamError };
    subscribe(): Pollable;
    drop(): void;
    [Symbol.dispose](): void;
}

export class MacroRegistry {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    registerScalar(name: string, parameters: string[], bodySql: string, options: Extopts | undefined): { tag: "ok"; val: boolean } | { tag: "err"; val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class OutputStream {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    blockingFlush(): { tag: "ok" } | { tag: "err"; val: StreamError };
    checkWrite(): { tag: "ok"; val: bigint } | { tag: "err"; val: StreamError };
    subscribe(): Pollable;
    write(contents: number[]): { tag: "ok" } | { tag: "err"; val: StreamError };
    drop(): void;
    [Symbol.dispose](): void;
}

export class Pollable {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    block(): void;
    drop(): void;
    [Symbol.dispose](): void;
}

export class PragmaCallback {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    static attach(driver: RuntimeGuestDriver, instanceHandle: number, handle: number): PragmaCallback;
    call(args: Duckvalue[]): { tag: "ok"; val: Duckvalue | undefined } | { tag: "err"; val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class PragmaRegistry {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    registerCall(name: string, arguments_: Funcarg[], returns: Logicaltype, callback: PragmaCallback, options: Extopts | undefined): { tag: "ok"; val: number } | { tag: "err"; val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class PreparedStatement {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    execute(params: Duckvalue[]): { tag: "ok"; val: QueryResult } | { tag: "err"; val: Duckerror };
    parameterCount(): number;
    drop(): void;
    [Symbol.dispose](): void;
}

export class ResultStream {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    close(): void;
    next(maxRows: number): { tag: "ok"; val: Row[] | undefined } | { tag: "err"; val: Duckerror };
    schema(): Columndef[];
    drop(): void;
    [Symbol.dispose](): void;
}

export class ScalarCallback {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    static attach(driver: RuntimeGuestDriver, instanceHandle: number, handle: number): ScalarCallback;
    call(args: Duckvalue[], ctx: Invokeinfo): { tag: "ok"; val: Duckvalue } | { tag: "err"; val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class ScalarRegistry {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    register(name: string, arguments_: Funcarg[], returns: Logicaltype, callback: ScalarCallback, options: Funcopts | undefined): { tag: "ok"; val: number } | { tag: "err"; val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class TableCallback {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    static attach(driver: RuntimeGuestDriver, instanceHandle: number, handle: number): TableCallback;
    call(args: Duckvalue[]): { tag: "ok"; val: Resultset } | { tag: "err"; val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class TableRegistry {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    register(name: string, arguments_: Funcarg[], columns: Columndef[], callback: TableCallback, options: Extopts | undefined): { tag: "ok"; val: number } | { tag: "err"; val: Duckerror };
    drop(): void;
    [Symbol.dispose](): void;
}

export class TerminalInput {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    drop(): void;
    [Symbol.dispose](): void;
}

export class TerminalOutput {
    constructor(driver: RuntimeGuestDriver, instanceHandle: number, handle: number, opts?: { owned?: boolean });
    readonly __handle: number;
    readonly __disposed: boolean;
    drop(): void;
    [Symbol.dispose](): void;
}

export interface RootExports {
    "duckdb:component/database": {
        open(path: string | undefined): { tag: "ok"; val: Connection } | { tag: "err"; val: string };
        openWithConfig(path: string | undefined, options: [string, string][]): { tag: "ok"; val: Connection } | { tag: "err"; val: string };
        close(conn: Connection): void;
        interrupt(conn: Connection): void;
        execute(conn: Connection, sql: string): { tag: "ok"; val: QueryResult } | { tag: "err"; val: Duckerror };
        openStream(conn: Connection, sql: string): { tag: "ok"; val: ResultStream } | { tag: "err"; val: Duckerror };
        prepare(conn: Connection, sql: string): { tag: "ok"; val: PreparedStatement } | { tag: "err"; val: Duckerror };
        queryArrow(conn: Connection, sql: string): { tag: "ok"; val: number[] } | { tag: "err"; val: Duckerror };
        createAppender(conn: Connection, schema: string | undefined, table: string): { tag: "ok"; val: Appender } | { tag: "err"; val: Duckerror };
        registerExtension(name: string, requires: Capabilitykind[]): { tag: "ok"; val: boolean } | { tag: "err"; val: string };
        listRegisteredExtensions(): ExtensionInfo[];
        handleUiRequest(method: string, path: string, headers: string, body: number[]): UiResponse | undefined;
        handleQuackRequest(body: number[]): number[] | undefined;
        Connection: typeof Connection;
        ResultStream: typeof ResultStream;
        PreparedStatement: typeof PreparedStatement;
        Appender: typeof Appender;
    };
    "duckdb:extension/config@4.0.0": {
        providerVersion(): string;
        listKeys(prefix: string | undefined): string[];
        getString(path: string): { tag: "ok"; val: string | undefined } | { tag: "err"; val: Configerror };
        getBool(path: string): { tag: "ok"; val: boolean | undefined } | { tag: "err"; val: Configerror };
        getI64(path: string): { tag: "ok"; val: bigint | undefined } | { tag: "err"; val: Configerror };
        getU64(path: string): { tag: "ok"; val: bigint | undefined } | { tag: "err"; val: Configerror };
        getF64(path: string): { tag: "ok"; val: number | undefined } | { tag: "err"; val: Configerror };
        getBytes(path: string): { tag: "ok"; val: number[] | undefined } | { tag: "err"; val: Configerror };
        getStringList(path: string): { tag: "ok"; val: string[] | undefined } | { tag: "err"; val: Configerror };
    };
    "duckdb:extension/logging@4.0.0": {
        log(level: Loglevel, message: string, target: string | undefined): void;
        logFields(level: Loglevel, message: string, fields: Logfield[]): void;
    };
    "duckdb:extension/runtime@4.0.0": {
        getCapability(kind: Capabilitykind): Capability | undefined;
        listCapabilities(): Capabilitykind[];
        ScalarCallback: typeof ScalarCallback;
        TableCallback: typeof TableCallback;
        AggregateCallback: typeof AggregateCallback;
        PragmaCallback: typeof PragmaCallback;
        CastCallback: typeof CastCallback;
        ScalarRegistry: typeof ScalarRegistry;
        TableRegistry: typeof TableRegistry;
        AggregateRegistry: typeof AggregateRegistry;
        PragmaRegistry: typeof PragmaRegistry;
        MacroRegistry: typeof MacroRegistry;
    };
}

export function bindRuntimeGuest(driver: RuntimeGuestDriver, instanceHandle: number): RootExports;

export interface RootImports {
    "duckdb:component/extension-loader-hooks"?: {
        "getPendingRegistrations"(): PendingRegistrations;
    };
    "duckdb:component/host-extension-loader"?: {
        "requestLoad"(name: string): boolean;
    };
    "duckdb:extension/callback-dispatch@4.0.0"?: {
        "callScalarBatchCol"(handle: number, args: Colvec[], ctx: Invokeinfo): { tag: "ok"; val: Colvec } | { tag: "err"; val: Duckerror };
        "callAggregateCol"(handle: number, args: Colvec[]): { tag: "ok"; val: Duckvalue } | { tag: "err"; val: Duckerror };
        "callCastCol"(handle: number, arg: Colvec): { tag: "ok"; val: Colvec } | { tag: "err"; val: Duckerror };
        "callScalar"(handle: number, args: Duckvalue[], ctx: Invokeinfo): { tag: "ok"; val: Duckvalue } | { tag: "err"; val: Duckerror };
        "callTable"(handle: number, args: Duckvalue[]): { tag: "ok"; val: Duckvalue[][] } | { tag: "err"; val: Duckerror };
        "callPragma"(handle: number, args: Duckvalue[]): { tag: "ok"; val: Duckvalue | undefined } | { tag: "err"; val: Duckerror };
    };
    "duckdb:extension/collation-host@4.0.0"?: {
        "collationList"(): CollationSpec[];
    };
    "duckdb:extension/files-host@4.0.0"?: {
        "fileOpen"(url: string): { tag: "ok"; val: FileOpenResult } | { tag: "err"; val: string };
        "fileRead"(handle: number, offset: bigint, len: number): { tag: "ok"; val: number[] } | { tag: "err"; val: string };
        "fileClose"(handle: number): { tag: "ok" } | { tag: "err"; val: string };
    };
    "duckdb:extension/index-host@4.0.0"?: {
        "indexTypeList"(): string[];
        "indexCreate"(typeName: string, indexName: string, dims: number): { tag: "ok"; val: number } | { tag: "err"; val: Duckerror };
        "indexAppend"(handle: number, rowids: bigint[], vectors: number[][]): { tag: "ok" } | { tag: "err"; val: Duckerror };
        "indexBuild"(handle: number): { tag: "ok" } | { tag: "err"; val: Duckerror };
        "indexSearch"(handle: number, query: number[], k: number): { tag: "ok"; val: IndexHit[] } | { tag: "err"; val: Duckerror };
        "indexDrop"(handle: number): { tag: "ok" } | { tag: "err"; val: Duckerror };
    };
    "duckdb:extension/optimizer-host@4.0.0"?: {
        "optimizerList"(): OptimizerSpec[];
        "callOptimize"(handle: number, planJson: string): { tag: "ok"; val: string | undefined } | { tag: "err"; val: Duckerror };
    };
    "duckdb:extension/parser-host@4.0.0"?: {
        "parserList"(): ParserSpec[];
        "callParse"(handle: number, query: string): { tag: "ok"; val: string | undefined } | { tag: "err"; val: Duckerror };
    };
    "duckdb:extension/pragma-host@4.0.0"?: {
        "pragmaList"(): PragmaSpec[];
    };
    "duckdb:extension/storage-host@4.0.0"?: {
        "storageListTypes"(): string[];
        "storageAttach"(dsn: string): { tag: "ok"; val: number } | { tag: "err"; val: Duckerror };
        "storageListTables"(catalog: number): { tag: "ok"; val: string[] } | { tag: "err"; val: Duckerror };
        "storageTableColumns"(catalog: number, table: string): { tag: "ok"; val: Columndef[] } | { tag: "err"; val: Duckerror };
        "storageScanOpen"(catalog: number, request: ScanRequest): { tag: "ok"; val: number } | { tag: "err"; val: Duckerror };
        "storageScanNext"(scan: number, maxRows: number): { tag: "ok"; val: Duckvalue[][] } | { tag: "err"; val: Duckerror };
        "storageScanClose"(scan: number): { tag: "ok"; val: boolean } | { tag: "err"; val: Duckerror };
        "storageBeginTransaction"(catalog: number): { tag: "ok"; val: number } | { tag: "err"; val: Duckerror };
        "storageCommitTransaction"(txn: number): { tag: "ok" } | { tag: "err"; val: Duckerror };
        "storageRollbackTransaction"(txn: number): { tag: "ok" } | { tag: "err"; val: Duckerror };
        "storageCreateTable"(txn: number, table: string, columns: Columndef[]): { tag: "ok" } | { tag: "err"; val: Duckerror };
        "storageInsertRows"(txn: number, table: string, rows: Duckvalue[][]): { tag: "ok"; val: bigint } | { tag: "err"; val: Duckerror };
        "storageDeleteRows"(txn: number, table: string, rowids: bigint[]): { tag: "ok"; val: bigint } | { tag: "err"; val: Duckerror };
        "storageUpdateRows"(txn: number, table: string, rowids: bigint[], updatedColumns: number[], rows: Duckvalue[][]): { tag: "ok"; val: bigint } | { tag: "err"; val: Duckerror };
    };
    "duckdb:extension/table-stream-host@4.0.0"?: {
        "filterableTableList"(): FilterableTable[];
        "tsOpenFiltered"(handle: number, args: Duckvalue[], projection: number[], filters: TsFilter[]): { tag: "ok"; val: TsOpenResult } | { tag: "err"; val: Duckerror };
        "tsNext"(handle: number, cursor: number, maxRows: number): { tag: "ok"; val: Duckvalue[][] } | { tag: "err"; val: Duckerror };
        "tsClose"(handle: number, cursor: number): { tag: "ok"; val: boolean } | { tag: "err"; val: Duckerror };
    };
    "tvm:memory/bytes@0.1.0"?: {
        "read"(ptr: Handle, len: number): { tag: "ok"; val: number[] } | { tag: "err"; val: TvmError };
        "write"(ptr: Handle, data: number[]): { tag: "ok" } | { tag: "err"; val: TvmError };
    };
    "tvm:memory/manager@0.1.0"?: {
        "createRegion"(kind: RegionKind, capacity: number): { tag: "ok"; val: number } | { tag: "err"; val: TvmError };
        "alloc"(regionId: number, size: number): { tag: "ok"; val: Handle } | { tag: "err"; val: TvmError };
        "dealloc"(ptr: Handle): { tag: "ok" } | { tag: "err"; val: TvmError };
    };
    "wasi:cli/environment@0.2.9"?: {
        "getEnvironment"(): [string, string][];
    };
    "wasi:cli/exit@0.2.9"?: {
        "exit"(status: { tag: "ok" } | { tag: "err" }): void;
    };
    "wasi:cli/stderr@0.2.9"?: {
        "getStderr"(): number;
    };
    "wasi:cli/stdin@0.2.9"?: {
        "getStdin"(): number;
    };
    "wasi:cli/stdout@0.2.9"?: {
        "getStdout"(): number;
    };
    "wasi:cli/terminal-stderr@0.2.9"?: {
        "getTerminalStderr"(): number | undefined;
    };
    "wasi:cli/terminal-stdin@0.2.9"?: {
        "getTerminalStdin"(): number | undefined;
    };
    "wasi:cli/terminal-stdout@0.2.9"?: {
        "getTerminalStdout"(): number | undefined;
    };
    "wasi:clocks/monotonic-clock@0.2.9"?: {
        "now"(): bigint;
        "subscribeInstant"(when: bigint): number;
        "subscribeDuration"(when: bigint): number;
    };
    "wasi:clocks/wall-clock@0.2.9"?: {
        "now"(): Datetime;
    };
    "wasi:filesystem/preopens@0.2.9"?: {
        "getDirectories"(): [number, string][];
    };
    "wasi:filesystem/types@0.2.9"?: {
        "[method]descriptor.read-via-stream"(self: number, offset: bigint): { tag: "ok"; val: number } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.write-via-stream"(self: number, offset: bigint): { tag: "ok"; val: number } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.append-via-stream"(self: number): { tag: "ok"; val: number } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.sync-data"(self: number): { tag: "ok" } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.get-flags"(self: number): { tag: "ok"; val: DescriptorFlags } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.set-size"(self: number, size: bigint): { tag: "ok" } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.read"(self: number, length: bigint, offset: bigint): { tag: "ok"; val: [number[], boolean] } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.write"(self: number, buffer: number[], offset: bigint): { tag: "ok"; val: bigint } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.read-directory"(self: number): { tag: "ok"; val: number } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.sync"(self: number): { tag: "ok" } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.create-directory-at"(self: number, path: string): { tag: "ok" } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.stat"(self: number): { tag: "ok"; val: DescriptorStat } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.stat-at"(self: number, pathFlags: PathFlags, path: string): { tag: "ok"; val: DescriptorStat } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.open-at"(self: number, pathFlags: PathFlags, path: string, openFlags: OpenFlags, flags: DescriptorFlags): { tag: "ok"; val: number } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.readlink-at"(self: number, path: string): { tag: "ok"; val: string } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.remove-directory-at"(self: number, path: string): { tag: "ok" } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.rename-at"(self: number, oldPath: string, newDescriptor: number, newPath: string): { tag: "ok" } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.unlink-file-at"(self: number, path: string): { tag: "ok" } | { tag: "err"; val: ErrorCode };
        "[method]descriptor.metadata-hash"(self: number): { tag: "ok"; val: MetadataHashValue } | { tag: "err"; val: ErrorCode };
        "[method]directory-entry-stream.read-directory-entry"(self: number): { tag: "ok"; val: DirectoryEntry | undefined } | { tag: "err"; val: ErrorCode };
    };
    "wasi:io/poll@0.2.9"?: {
        "[method]pollable.block"(self: number): void;
        "poll"(in_: number[]): number[];
    };
    "wasi:io/streams@0.2.9"?: {
        "[method]input-stream.read"(self: number, len: bigint): { tag: "ok"; val: number[] } | { tag: "err"; val: StreamError };
        "[method]input-stream.subscribe"(self: number): number;
        "[method]output-stream.check-write"(self: number): { tag: "ok"; val: bigint } | { tag: "err"; val: StreamError };
        "[method]output-stream.write"(self: number, contents: number[]): { tag: "ok" } | { tag: "err"; val: StreamError };
        "[method]output-stream.blocking-flush"(self: number): { tag: "ok" } | { tag: "err"; val: StreamError };
        "[method]output-stream.subscribe"(self: number): number;
    };
    "wasi:random/insecure-seed@0.2.9"?: {
        "insecureSeed"(): [bigint, bigint];
    };
    "wasi:random/random@0.2.9"?: {
        "getRandomBytes"(len: bigint): number[];
    };
}

export function registerHostProviders(driver: RuntimeGuestDriver, impls?: RootImports): Record<string, number>;

