//! ST_Transform(geom_wkt VARCHAR, from_srid INTEGER, to_srid INTEGER) -> VARCHAR
//!
//! Reprojects a WKT geometry from one EPSG CRS to another via the SINGLE
//! resident, SHARED `compose:dynlink` gdal provider. The scalar resolves the
//! resident `gdal` provider on the host's `compose:dynlink/linker` and invokes
//! its `transform` method (SpatialRef::from_epsg + a coordinate Transform + a
//! wkt/geo-types coordinate walk, re-emitted as WKT). EPSG codes are resolved
//! by PROJ's proj.db, embedded ONCE in the resident gdal-provider (not
//! wac-inlined into this extension). NULL on any failure.
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{atomic::{AtomicU32, Ordering}, Mutex, OnceLock};
use wit_bindgen::rt::string::String;
use wit_bindgen::rt::vec::Vec;

wit_bindgen::generate!({ path: "./wit", world: "spatialproj", generate_all });

use compose::dynlink::linker;
use duckdb::extension::{runtime, types};
use exports::duckdb::extension::guest;

struct Extension;

/// The provider id registered in the host (DUCKLINK_PROVIDERS=gdal=...).
const GDAL_ID: &str = "gdal";

/// The msgpack `transform` request the gdal provider expects:
/// `{"wkt": <string>, "from_srid": <int32>, "to_srid": <int32>}`.
#[derive(Serialize)]
struct TransformReq {
    wkt: std::string::String,
    from_srid: i32,
    to_srid: i32,
}

/// The msgpack `transform` response: `{"wkt": <string>}`.
#[derive(Deserialize)]
struct TransformResp {
    wkt: std::string::String,
}

impl guest::Guest for Extension {
    fn load() -> Result<types::Loadresult, types::Duckerror> {
        register_scalars()?;
        Ok(types::Loadresult {
            name: "spatialproj".into(),
            version: Some(env!("CARGO_PKG_VERSION").into()),
            requires: Vec::new().into(),
        })
    }
    fn reconfigure(_k: Vec<String>) -> Result<bool, types::Duckerror> { Ok(false) }
    fn shutdown() -> Result<bool, types::Duckerror> { Ok(false) }
}

fn text_arg(args: &[types::Duckvalue], i: usize) -> Option<String> {
    match args.get(i) { Some(types::Duckvalue::Text(s)) => Some(s.clone()), _ => None }
}
fn i32_arg(args: &[types::Duckvalue], i: usize) -> Option<i32> {
    match args.get(i) {
        Some(types::Duckvalue::Int64(v)) => Some(*v as i32),
        Some(types::Duckvalue::Int32(v)) => Some(*v),
        _ => None,
    }
}

/// Reproject one WKT geometry string via the resident gdal provider. Returns
/// None on any failure (-> SQL NULL): bad SRID, provider absent/unresolvable,
/// msgpack error, or a transform error surfaced as the provider's Err.
fn transform_wkt(wkt_in: &str, from_srid: i32, to_srid: i32) -> Option<std::string::String> {
    if from_srid <= 0 || to_srid <= 0 {
        return None;
    }

    // 1. msgpack-encode the request (named-key map, matching the provider's wire
    //    format).
    let req = TransformReq {
        wkt: wkt_in.into(),
        from_srid,
        to_srid,
    };
    let payload = rmp_serde::to_vec_named(&req).ok()?;

    // 2. resolve the shared, resident gdal provider.
    let inst = linker::resolve_by_id(GDAL_ID).ok()?;

    // 3. invoke("transform", payload) -> opaque bytes (GDAL/PROJ reprojection on
    //    the resident provider). The provider's Err (bad SRID / parse / transform
    //    failure) becomes None here -> SQL NULL, matching the old behaviour.
    let resp_bytes = inst.invoke("transform", &payload).ok()?;

    // 4. msgpack-decode {"wkt": <string>}.
    let resp: TransformResp = rmp_serde::from_slice(&resp_bytes).ok()?;
    Some(resp.wkt)
}

// Per-row scalar logic, UNCHANGED from the major-3 hand-written impl. The
// major-4 columnar dispatch (call-scalar-batch-col etc.) is generated by
// `datalink_extcore::columnar_bridge!`, which bridges `colvec` <-> row and
// delegates here.
fn scalar(handle: u32, args: Vec<types::Duckvalue>, _c: types::Invokeinfo) -> Result<types::Duckvalue, types::Duckerror> {
    let _which = handlers().lock().unwrap().get(&handle).copied()
        .ok_or_else(|| types::Duckerror::Internal("unknown scalar handle".into()))?;
    let wkt_in = match text_arg(&args, 0) { Some(s) => s, None => return Ok(types::Duckvalue::Null) };
    let from = match i32_arg(&args, 1) { Some(v) => v, None => return Ok(types::Duckvalue::Null) };
    let to = match i32_arg(&args, 2) { Some(v) => v, None => return Ok(types::Duckvalue::Null) };
    Ok(match transform_wkt(&wkt_in, from, to) {
        Some(s) => types::Duckvalue::Text(s.into()),
        None => types::Duckvalue::Null,
    })
}

datalink_extcore::columnar_bridge! {
    types = duckdb::extension::types;
    column_types = duckdb::extension::column_types;
    callback_dispatch = exports::duckdb::extension::callback_dispatch;
    target = Extension;
    scalar = scalar;
}

export!(Extension);

fn register_scalars() -> Result<(), types::Duckerror> {
    let cap = runtime::get_capability(types::Capabilitykind::Scalar)
        .ok_or_else(|| types::Duckerror::Internal("no scalar capability".into()))?;
    let reg = match cap { runtime::Capability::Scalar(r) => r, _ => return Err(types::Duckerror::Internal("bad capability".into())) };
    let det = types::Funcflags::DETERMINISTIC | types::Funcflags::STATELESS;
    let h = NEXT.fetch_add(1, Ordering::Relaxed);
    handlers().lock().unwrap().insert(h, S::Transform);
    reg.register("ST_Transform", &[
        runtime::Funcarg { name: Some("geom_wkt".into()), logical: types::Logicaltype::Text },
        runtime::Funcarg { name: Some("from_srid".into()), logical: types::Logicaltype::Int32 },
        runtime::Funcarg { name: Some("to_srid".into()), logical: types::Logicaltype::Int32 }],
        &types::Logicaltype::Text, runtime::ScalarCallback::new(h),
        Some(&runtime::Funcopts {
            description: Some("Reproject a WKT geometry between EPSG CRS via the resident compose:dynlink gdal provider".into()),
            tags: vec!["geo".into(), "gdal".into()],
            attributes: det,
        }))?;
    Ok(())
}

#[derive(Clone, Copy, PartialEq)] enum S { Transform }
static NEXT: AtomicU32 = AtomicU32::new(1);
static HANDLERS: OnceLock<Mutex<HashMap<u32, S>>> = OnceLock::new();
fn handlers() -> &'static Mutex<HashMap<u32, S>> { HANDLERS.get_or_init(|| Mutex::new(HashMap::new())) }
