// In-browser extension host, runtime-guest lane.
//
// Boots each DuckDB extension component through the SAME wasm-cm runtime-guest
// driver that ran the core (`run-core.mjs::createDuckLinkDriver`), provides
// the extension's `duckdb:extension/runtime|catalog|files` imports as JS
// closures (registrations flow into a per-extension `pending` record), and
// exposes the CORE-side imports the core component needs
// (`host-extension-loader`, `extension-loader-hooks`, `callback-dispatch`) via
// {@link createExtensionHost#coreImports}. Callback dispatch forwards to each
// loaded extension's own `callback-dispatch` export through the same driver's
// `callExport`.
//
// # Per-extension bindings
//
// Each extension component has its own WIT surface (runtime/catalog/files
// interface versions, guest.load / callback-dispatch exports), so each needs
// its own generated bindings pair — regenerated by `web/generate.sh` alongside
// the core bindings. The bindings live at
// `web/bindings-runtime-guest/<name>.runtime-guest.mjs` and expose the same
// `registerHostProviders` + `bindRuntimeGuest` shape the core bindings do.
//
// # Instantiation is async, dispatch is sync (from the guest's POV)
//
// Component instantiation goes through the driver's JSPI-async
// `instantiateWithImports`, so `preload()` is async. Once loaded, the core
// calls `request-load` synchronously; the cached result is returned. Callback
// dispatch back into the extension is byte-frame in / byte-frame out through
// the driver, wrapped as async by the generated bindings (JSPI-safe).

import { createWasiProviders } from '@wasmos/runtime-guest-bridge'

// -----------------------------------------------------------------------------
// The wasi interface set an extension component may import. Extensions built
// against different wasi tags (cron / cron_scheduler are @0.2.3, aba is
// @0.2.9) resolve through the polyfill's version-agnostic matcher, but the
// bindings' `registerHostProviders` looks up impls by the EXACT interface
// string the wasm imports — so both tag sets are requested up front and the
// bindings pick whatever the extension binary actually declares. Missing
// interfaces are silently dropped by `createWasiProviders`.
// -----------------------------------------------------------------------------
const EXT_WASI_INTERFACES = Object.freeze([
  // @0.2.3 (cron, cron_scheduler)
  'wasi:cli/environment@0.2.3',
  'wasi:cli/exit@0.2.3',
  'wasi:cli/stderr@0.2.3',
  'wasi:cli/stdin@0.2.3',
  'wasi:cli/stdout@0.2.3',
  'wasi:clocks/wall-clock@0.2.3',
  'wasi:clocks/monotonic-clock@0.2.3',
  'wasi:filesystem/preopens@0.2.3',
  'wasi:filesystem/types@0.2.3',
  'wasi:io/error@0.2.3',
  'wasi:io/poll@0.2.3',
  'wasi:io/streams@0.2.3',
  'wasi:random/random@0.2.3',
  'wasi:random/insecure-seed@0.2.3',
  // @0.2.9 (aba, sample_extension when rebuilt)
  'wasi:cli/environment@0.2.9',
  'wasi:cli/exit@0.2.9',
  'wasi:cli/stderr@0.2.9',
  'wasi:cli/stdin@0.2.9',
  'wasi:cli/stdout@0.2.9',
  'wasi:cli/terminal-input@0.2.9',
  'wasi:cli/terminal-output@0.2.9',
  'wasi:cli/terminal-stdin@0.2.9',
  'wasi:cli/terminal-stdout@0.2.9',
  'wasi:cli/terminal-stderr@0.2.9',
  'wasi:clocks/wall-clock@0.2.9',
  'wasi:clocks/monotonic-clock@0.2.9',
  'wasi:filesystem/preopens@0.2.9',
  'wasi:filesystem/types@0.2.9',
  'wasi:io/error@0.2.9',
  'wasi:io/poll@0.2.9',
  'wasi:io/streams@0.2.9',
  'wasi:random/random@0.2.9',
  'wasi:random/insecure-seed@0.2.9',
])

// -----------------------------------------------------------------------------
// Per-extension bindings loader. The generated files are static ES modules
// with a top-level export contract; Vite handles the dynamic import in dev
// mode. Extensions absent from web/public/ (and therefore absent from
// `bindings-runtime-guest/`) reject with a clear error rather than the
// module-not-found spelunk.
// -----------------------------------------------------------------------------
// Vite's dep scan tries to statically resolve every `import('./…')` literal
// at load time, even inside a function body — a missing bindings file (e.g.
// sample_extension.wasm isn't staged in this worktree) then 500s the whole
// page, not just the branch that tries to load it. Route each loader through
// `import.meta.glob` (Vite's escape hatch for "look at everything matching
// this pattern, but only fetch when I call the returned factory"), so any
// bindings file present in the worktree resolves lazily and a missing one
// throws only when preload() actually reaches for it.
const EXT_BINDINGS_GLOB = import.meta.glob('./bindings-runtime-guest/*.runtime-guest.mjs')
function bindingsFor(name) {
  const key = `./bindings-runtime-guest/${name}.runtime-guest.mjs`
  const loader = EXT_BINDINGS_GLOB[key]
  if (!loader) return null
  return loader
}

// Fixed callback-registry handles handed out by `getCapability`. The extension
// treats these as resource-handle numbers (own/borrow); on dispatch back into
// `[method]<registry>.register` we ignore `self` and use `pending.<kind>` as
// the underlying store. One handle per registry keeps the shape simple; the
// extension never needs multiple registry instances.
const REGISTRY = Object.freeze({
  SCALAR: 0x10, TABLE: 0x11, AGGREGATE: 0x12, PRAGMA: 0x13, MACRO: 0x14,
})

// -----------------------------------------------------------------------------
// Build the impls the extension's `registerHostProviders` needs — the
// `duckdb:extension/{runtime,catalog,files,types,column-types}` interfaces.
// Registration calls accumulate into `pending`, which the CORE later drains via
// `extension-loader-hooks#getPendingRegistrations`. Callback handles are
// allocated monotonically inside this closure so they never collide across
// registry kinds.
// -----------------------------------------------------------------------------
function buildExtensionImports(pending) {
  let nextCbId = 1
  const alloc = () => nextCbId++
  const tableHandles = new Map() // table-callback handle -> function name (replacement-scan lookup)

  const runtime = {
    // Resource constructors — the extension passes a callback index u32 in;
    // the host returns an opaque own-handle it later hands back to
    // `<registry>.register` alongside the declaration metadata.
    '[constructor]scalar-callback': (_idx) => alloc(),
    '[constructor]table-callback': (_idx) => alloc(),
    '[constructor]aggregate-callback': (_idx) => alloc(),
    '[constructor]pragma-callback': (_idx) => alloc(),
    '[constructor]cast-callback': (_idx) => alloc(),
    '[method]scalar-registry.register': (_self, name, args, returns, callback, options) => {
      pending.scalars.push({ name, arguments: args, returns, callbackHandle: callback, options })
      return { tag: 'ok', val: alloc() }
    },
    '[method]table-registry.register': (_self, name, args, columns, callback, options) => {
      const handle = alloc()
      pending.tables.push({ name, arguments: args, columns, callbackHandle: callback, options })
      tableHandles.set(handle, name)
      return { tag: 'ok', val: handle }
    },
    '[method]aggregate-registry.register': (_self, name, args, returns, callback, options) => {
      pending.aggregates.push({ name, arguments: args, returns, callbackHandle: callback, options })
      return { tag: 'ok', val: alloc() }
    },
    '[method]pragma-registry.register-call': () => ({ tag: 'ok', val: alloc() }),
    '[method]macro-registry.register-scalar': () => ({ tag: 'ok', val: true }),
    getCapability: (kind) => {
      const tag = typeof kind === 'string' ? kind : kind?.tag
      switch (tag) {
        case 'scalar': return { tag: 'scalar', val: REGISTRY.SCALAR }
        case 'table': return { tag: 'table', val: REGISTRY.TABLE }
        case 'aggregate': return { tag: 'aggregate', val: REGISTRY.AGGREGATE }
        case 'pragma': return { tag: 'pragma', val: REGISTRY.PRAGMA }
        case 'macro': return { tag: 'macro', val: REGISTRY.MACRO }
        default: return undefined
      }
    },
    listCapabilities: () => ['scalar', 'table', 'aggregate', 'pragma', 'macro'],
  }

  const catalog = {
    registerLogicalType: (ty) => {
      pending.logicalTypes.push({ name: ty.name, physical: ty.physical })
      return { tag: 'ok', val: alloc() }
    },
    registerCast: (spec, cb) => {
      pending.casts.push({ source: spec.from, target: spec.to, callbackHandle: cb })
      return { tag: 'ok', val: undefined }
    },
    registerMacro: (def) => {
      pending.macros.push({
        schema: def.schema, name: def.name,
        parameters: def.parameters, definitionSql: def.definitionSql,
      })
      return { tag: 'ok', val: undefined }
    },
  }

  const files = {
    registerReplacementScan: (scan) => {
      pending.replacementScans.push({
        extensions: scan.extensions,
        functionName: tableHandles.get(scan.tableFunction) ?? '',
      })
      return { tag: 'ok', val: alloc() }
    },
    registerCopyHandler: () => {
      return { tag: 'err', val: { tag: 'internal', val: 'copy handlers are not supported' } }
    },
  }

  // Return keys are matched against the extension bindings' hardcoded `_iface`
  // list. Both @4.0.0 and @5.0.0 tags are supplied so a mismatch in extension
  // WIT version doesn't produce "missing impl" errors during registration.
  const perTag = (tag) => ({
    [`duckdb:extension/runtime@${tag}`]: runtime,
    [`duckdb:extension/catalog@${tag}`]: catalog,
    [`duckdb:extension/files@${tag}`]: files,
    [`duckdb:extension/types@${tag}`]: {},
    [`duckdb:extension/column-types@${tag}`]: {},
  })
  return { ...perTag('4.0.0'), ...perTag('5.0.0') }
}

// -----------------------------------------------------------------------------
// Look up the extension's own callback-dispatch export off the bound api. The
// export lives under `duckdb:extension/callback-dispatch@<ver>` — extensions
// built against @4.0.0 vs @5.0.0 use different keys, so try each in order.
// -----------------------------------------------------------------------------
function pickCallbackDispatch(api) {
  return (
    api['duckdb:extension/callback-dispatch@4.0.0']
    ?? api['duckdb:extension/callback-dispatch@5.0.0']
    ?? null
  )
}
function pickGuest(api) {
  return (
    api['duckdb:extension/guest@4.0.0']
    ?? api['duckdb:extension/guest@5.0.0']
    ?? null
  )
}

// -----------------------------------------------------------------------------
// createExtensionHost({driver, polyfill})
//
// Both `driver` and `polyfill` come from `createDuckLinkDriver()` in
// `run-core.mjs`. The host loads extensions into the shared driver so callback
// dispatch (core -> extension) is a straight `driver.callExport` — no separate
// driver instance per extension, no cross-runtime hopping.
// -----------------------------------------------------------------------------
export function createExtensionHost({ driver, polyfill }) {
  if (!driver) throw new Error('createExtensionHost: {driver} is required — build it with createDuckLinkDriver() in run-core.mjs')
  if (!polyfill) throw new Error('createExtensionHost: {polyfill} is required — build it with createDuckLinkDriver() in run-core.mjs')

  const loaded = new Map() // name -> { api, pending, callbackDispatch }
  let drained = false

  async function preload(name, bytes) {
    const loader = bindingsFor(name)
    if (!loader) {
      throw new Error(
        `extension-host: no runtime-guest bindings for extension '${name}'. ` +
        `Add its wasm to web/public/ and rerun 'npm run generate' — the recipe emits ` +
        `web/bindings-runtime-guest/${name}.runtime-guest.mjs.`,
      )
    }
    const bindings = await loader()
    const { registerHostProviders, bindRuntimeGuest } = bindings

    const pending = emptyPending()
    const wasiImpls = await createWasiProviders({ polyfill, interfaces: EXT_WASI_INTERFACES })
    const impls = { ...wasiImpls, ...buildExtensionImports(pending) }

    const componentHandle = driver.parseComponent(bytes)
    const providerHandles = registerHostProviders(driver, impls)
    const imports = Object.entries(providerHandles).map(([interfaceName, providerHandle]) => ({
      interfaceName, providerHandle,
    }))
    const instanceHandle = await driver.instantiateWithImports(componentHandle, imports)
    const api = bindRuntimeGuest(driver, instanceHandle)

    const guest = pickGuest(api)
    const callbackDispatch = pickCallbackDispatch(api)
    if (!guest) {
      throw new Error(`extension-host: extension '${name}' bindings expose no duckdb:extension/guest — the wasm's export surface has drifted from what wit-js-bindgen emitted; rerun 'npm run generate'.`)
    }
    if (!callbackDispatch) {
      throw new Error(`extension-host: extension '${name}' bindings expose no duckdb:extension/callback-dispatch — cannot forward core-side dispatches. Rerun 'npm run generate'.`)
    }

    // guest.load() runs the extension's registrations. Registrations flow into
    // `pending` through the runtime/catalog/files impls above.
    const loadRes = await guest.load()
    if (loadRes && loadRes.tag === 'err') {
      const errVal = loadRes.val
      const msg = typeof errVal === 'string' ? errVal : `${errVal?.tag ?? 'err'}: ${errVal?.val ?? JSON.stringify(errVal)}`
      throw new Error(`extension-host: guest.load() failed for '${name}': ${msg}`)
    }

    loaded.set(name, { api, pending, callbackDispatch })
  }

  // Imports the CORE component needs (feed via `instantiateCore(..., host.coreImports())`).
  function coreImports() {
    // Round-robin over loaded extensions to route callback handles. Extensions
    // registered non-overlapping handle spaces in `alloc()`, so any handle
    // resolves to at most one extension. The demo entries load either one
    // extension (browser-ext, browser-aba) or two (browser-cron with cron +
    // cron_scheduler) — a naive first-match dispatch is enough.
    const dispatch = (method) => async (...args) => {
      for (const { callbackDispatch } of loaded.values()) {
        const fn = callbackDispatch[method]
        if (typeof fn === 'function') {
          return await fn(...args)
        }
      }
      throw new Error(`extension-host.coreImports.callback-dispatch: '${method}' not exposed by any loaded extension`)
    }

    return {
      'duckdb:component/host-extension-loader': {
        requestLoad: (name) => loaded.has(name),
      },
      'duckdb:component/extension-loader-hooks': {
        getPendingRegistrations: () => {
          if (drained) return emptyPending()
          drained = true
          const all = emptyPending()
          for (const { pending } of loaded.values()) {
            for (const k of Object.keys(all)) all[k].push(...(pending[k] ?? []))
          }
          return all
        },
      },
      // The core imports @4.0.0. Every method the router touches must have a
      // shim — the generated router throws "missing impl" on any unbound key
      // rather than defaulting to undefined.
      'duckdb:extension/callback-dispatch@4.0.0': {
        callScalarBatchCol: dispatch('callScalarBatchCol'),
        callAggregateCol: dispatch('callAggregateCol'),
        callCastCol: dispatch('callCastCol'),
        callScalar: dispatch('callScalar'),
        callTable: dispatch('callTable'),
        callPragma: dispatch('callPragma'),
      },
    }
  }

  return { preload, coreImports }
}

function emptyPending() {
  return {
    scalars: [], tables: [], aggregates: [], macros: [],
    replacementScans: [], logicalTypes: [], casts: [],
  }
}
