// Boot the DuckLink core wasip2 component in the browser via wasm-cm's
// portable `runtime-guest` interpreter (`@tegmentum/wasmos-browser` +
// `@wasmos/runtime-guest-bridge`), and adapt `duckdb:component/database`
// to `runQuery(bytes, sql)`.
//
// Same layout the elena-wasm sibling `@wasmos/dataset-ducklink` package
// uses (W1c in `docs/vela-wasmos-browser-runtime.md`). No jco transpile
// step, no wasi-polyfill `RuntimeBindgen` — the runtime-guest driver
// speaks the wasm-cm tagged byte-frame codec directly, and the WASI
// imports are satisfied through a byte-frame provider built from
// wasi-polyfill's plugin implementations by the bridge.
//
// The JS type surface (`Duckvalue`, `Columndef`, `DuckdbComponentDatabase`,
// …) is imported as JSDoc @typedef from the runtime-guest bindings
// generated by `wit-js-bindgen --role runtime-guest` from the built
// `ducklink_core.wasm` binary (see `web/generate.sh` — the recipe now
// derives bindings from the WASM, not from the WIT source tree, so
// import names stay in lockstep with whatever the wasm actually links
// against).
//
// Regenerate the bindings with `npm run generate`. The generated file
// pair lives at `web/bindings-runtime-guest/libduckdb.runtime-guest.{mjs,d.mts}`.

/**
 * @typedef {import('./bindings-runtime-guest/libduckdb.runtime-guest.d.mts').Duckvalue} Duckvalue
 * @typedef {import('./bindings-runtime-guest/libduckdb.runtime-guest.d.mts').Columndef} Columndef
 * @typedef {import('./bindings-runtime-guest/libduckdb.runtime-guest.d.mts').Queryresult} Queryresult
 */

import { bootRuntimeGuestFromUrl } from '@tegmentum/wasmos-browser'
import runtimeGuestUrl from '@tegmentum/wasmos-browser/runtime-guest.wasm?url'
import { createWasiProviders } from '@wasmos/runtime-guest-bridge'
import { createPolyfill, createPolicy } from '@tegmentum/wasi-polyfill/wasip2'
import * as cliPlugins from '@tegmentum/wasi-polyfill/wasip2/plugins/cli'
import * as ioPlugins from '@tegmentum/wasi-polyfill/wasip2/plugins/io'
import * as fsPlugins from '@tegmentum/wasi-polyfill/wasip2/plugins/filesystem'
import * as clocksPlugins from '@tegmentum/wasi-polyfill/wasip2/plugins/clocks'
import * as randomPlugins from '@tegmentum/wasi-polyfill/wasip2/plugins/random'
import {
  registerHostProviders,
  bindRuntimeGuest,
} from './bindings-runtime-guest/libduckdb.runtime-guest.mjs'

// -----------------------------------------------------------------------------
// Interface set the built `ducklink_core.wasm` currently imports. Tagged
// @0.2.9 to match the ducklink build; the wasi-polyfill plugins register at
// @0.2.0 and the version-agnostic resolver serves them against these queries.
// Kept in sync by `generate.sh` (which greps the emitted bindings on
// regeneration) — bump these strings if the wasm build shifts to a newer wasi
// tag.
// -----------------------------------------------------------------------------
export const CORE_WASI_INTERFACES = Object.freeze([
  'wasi:cli/environment@0.2.9',
  'wasi:cli/exit@0.2.9',
  'wasi:cli/stdin@0.2.9',
  'wasi:cli/stdout@0.2.9',
  'wasi:cli/stderr@0.2.9',
  'wasi:cli/terminal-input@0.2.9',
  'wasi:cli/terminal-output@0.2.9',
  'wasi:cli/terminal-stdin@0.2.9',
  'wasi:cli/terminal-stdout@0.2.9',
  'wasi:cli/terminal-stderr@0.2.9',
  'wasi:clocks/monotonic-clock@0.2.9',
  'wasi:clocks/wall-clock@0.2.9',
  'wasi:filesystem/preopens@0.2.9',
  'wasi:filesystem/types@0.2.9',
  'wasi:io/error@0.2.9',
  'wasi:io/poll@0.2.9',
  'wasi:io/streams@0.2.9',
  'wasi:random/random@0.2.9',
  'wasi:random/insecure-seed@0.2.9',
])

// -----------------------------------------------------------------------------
// duckdb:* + tvm:memory host stubs. Every duckdb:extension/*@4.0.0 and
// tvm:memory/*@0.1.0 interface the wasm imports needs a provider slot; the
// plain-query smoke path never dispatches through them, so throw-on-call is a
// legible failure surface if anything trips them. Extension loading + TVM
// spill are separate lanes (extension-host.mjs, tvm-host.mjs) that plug in
// via the `additionalImpls` seam on `instantiateCore`.
// -----------------------------------------------------------------------------
export function duckdbStubImpls() {
  const unavailable = (label) => () => { throw new Error(`${label}: not wired in the runtime-guest smoke boot`) }
  return {
    'duckdb:component/host-extension-loader': { requestLoad: () => false },
    'duckdb:component/extension-loader-hooks': {
      getPendingRegistrations: () => ({
        scalars: [], tables: [], aggregates: [], macros: [],
        replacementScans: [], logicalTypes: [], casts: [],
      }),
    },
    // Typedef-only WIT interfaces — the emitter allocates provider slots but
    // has no router entries; an empty impl is enough to satisfy shape checks.
    'duckdb:extension/types@4.0.0': {},
    'duckdb:extension/column-types@4.0.0': {},
    'duckdb:extension/callback-dispatch@4.0.0': {
      callScalarBatchCol: unavailable('callback-dispatch.call-scalar-batch-col'),
      callAggregateCol: unavailable('callback-dispatch.call-aggregate-col'),
      callCastCol: unavailable('callback-dispatch.call-cast-col'),
      callScalar: unavailable('callback-dispatch.call-scalar'),
      callTable: unavailable('callback-dispatch.call-table'),
      callPragma: unavailable('callback-dispatch.call-pragma'),
    },
    'duckdb:extension/collation-host@4.0.0': { collationList: () => [] },
    'duckdb:extension/files-host@4.0.0': {
      fileOpen: () => ({ tag: 'err', val: 'files-host not wired' }),
      fileRead: () => ({ tag: 'err', val: 'files-host not wired' }),
      fileClose: () => ({ tag: 'err', val: 'files-host not wired' }),
    },
    'duckdb:extension/index-host@4.0.0': {
      indexTypeList: () => [],
      indexCreate: () => ({ tag: 'err', val: { tag: 'internal', val: 'index-host not wired' } }),
      indexAppend: () => ({ tag: 'err', val: { tag: 'internal', val: 'index-host not wired' } }),
      indexBuild: () => ({ tag: 'err', val: { tag: 'internal', val: 'index-host not wired' } }),
      indexSearch: () => ({ tag: 'err', val: { tag: 'internal', val: 'index-host not wired' } }),
      indexDrop: () => ({ tag: 'err', val: { tag: 'internal', val: 'index-host not wired' } }),
    },
    'duckdb:extension/optimizer-host@4.0.0': {
      optimizerList: () => [],
      callOptimize: () => ({ tag: 'err', val: { tag: 'internal', val: 'optimizer-host not wired' } }),
    },
    'duckdb:extension/parser-host@4.0.0': {
      parserList: () => [],
      callParse: () => ({ tag: 'err', val: { tag: 'internal', val: 'parser-host not wired' } }),
    },
    'duckdb:extension/pragma-host@4.0.0': { pragmaList: () => [] },
    'duckdb:extension/storage-host@4.0.0': {},
    'duckdb:extension/table-stream-host@4.0.0': {},
    'tvm:memory/types@0.1.0': {},
    'tvm:memory/bytes@0.1.0': {
      read: unavailable('tvm:memory/bytes.read'),
      write: unavailable('tvm:memory/bytes.write'),
    },
    'tvm:memory/manager@0.1.0': {
      createRegion: unavailable('tvm:memory/manager.create-region'),
      alloc: unavailable('tvm:memory/manager.alloc'),
      dealloc: unavailable('tvm:memory/manager.dealloc'),
    },
  }
}

// -----------------------------------------------------------------------------
// Build a wasi-polyfill instance with the standard cli/io/filesystem/clocks/
// random plugin bundle registered, backed by a writable in-memory `/` preopen +
// a pre-created `/.duckdb` (DuckDB's non-recursive `CreateDirectory` succeeds
// on `LOAD` once the directory exists).
//
// Static imports here — the bridge's `createStandardPolyfill` uses runtime
// dynamic imports to keep its own module cost off callers who supply their own
// polyfill, but Vite's dev server can't rewrite variable-held dynamic import
// specifiers, so under Vite the bare specifier reaches the browser as-is and
// fails to resolve. Constructing the polyfill directly with static imports
// side-steps that entirely.
// -----------------------------------------------------------------------------
export function buildPolyfill() {
  const policy = createPolicy({
    defaultAllow: true,
    preopens: [{ path: '/' }],
    mkdirs: ['/.duckdb'],
  })
  const polyfill = createPolyfill({ policy })
  for (const plugin of [
    ...(cliPlugins.cliPlugins ?? []),
    ...(fsPlugins.filesystemPlugins ?? []),
    ...(ioPlugins.ioPlugins ?? []),
    ...(clocksPlugins.clocksPlugins ?? []),
    ...(randomPlugins.randomPlugins ?? []),
  ]) {
    polyfill.registerPlugin(plugin)
  }
  return polyfill
}

// -----------------------------------------------------------------------------
// One-shot driver bootstrap. Returns `{driver, polyfill}` — the shared
// runtime-guest driver every component instantiation in the page rides on,
// plus the wasi-polyfill instance whose plugins back both core AND extension
// wasi imports. `instantiateCore` and `extension-host.mjs::createExtensionHost`
// both accept an optional pre-built bundle here so an entry point that boots
// several components (core + one or more extensions) shares one driver / one
// polyfill across all of them.
// -----------------------------------------------------------------------------
export async function createDuckLinkDriver({ jspi = 'auto' } = {}) {
  const polyfill = buildPolyfill()
  // `jspi: 'auto'` — Chromium/V8 refuses synchronous `WebAssembly.Compile`
  // on the main thread for buffers >8 MB (the DuckLink core wasm is ~44 MB).
  // JSPI mode routes compile + instantiate through the async host-compile /
  // host-instantiate-with-imports paths that use `WebAssembly.compile`
  // (asynchronous) internally, so the size cap does not trip. Chrome 137+
  // and Playwright's bundled Chromium have JSPI; older runtimes fall back
  // to the sync path and hit the 8 MB wall.
  const { driver } = await bootRuntimeGuestFromUrl(runtimeGuestUrl, { jspi })
  if (typeof driver.registerRouter !== 'function') {
    throw new Error(
      'run-core: @tegmentum/wasmos-browser boot did not return a driver with a ' +
      '`registerRouter` method — the runtime-guest emitter cannot bind provider routers. ' +
      'Update @tegmentum/wasmos-browser to a build that surfaces registerRouter on the driver.',
    )
  }
  return { driver, polyfill }
}

// -----------------------------------------------------------------------------
// Boot the runtime-guest driver (or reuse a pre-built one), register every
// host provider (WASI byte-frame impls from the bridge + inline duckdb/tvm
// stubs), parse the component bytes, instantiate with the resolved import
// handles, and pull the `duckdb:component/database` interface off the bound
// export surface.
//
// `additionalImpls` is spread OVER the stubs so a caller who has richer
// duckdb:* / tvm:memory backends (a browser TVM host, an extension-host on the
// runtime-guest lane) can override any subset by interface key.
// `options.driverBundle` opts the caller out of building a fresh driver +
// polyfill — pass one from `createDuckLinkDriver()` when the same page will
// also boot extension components through the same driver.
// -----------------------------------------------------------------------------
export async function instantiateCore(componentBytes, additionalImpls = {}, options = {}) {
  const bundle = options.driverBundle ?? (await createDuckLinkDriver({ jspi: 'auto' }))
  const { driver, polyfill } = bundle

  const wasiImpls = await createWasiProviders({ polyfill, interfaces: CORE_WASI_INTERFACES })
  const impls = { ...wasiImpls, ...duckdbStubImpls(), ...additionalImpls }

  const componentHandle = driver.parseComponent(componentBytes)
  const providerHandles = registerHostProviders(driver, impls)
  const imports = Object.entries(providerHandles).map(([interfaceName, providerHandle]) => ({
    interfaceName,
    providerHandle,
  }))
  // In JSPI mode `instantiateWithImports` returns a Promise. The sync path
  // returns a number directly; awaiting a number is a no-op, so this line
  // is safe on both.
  const instanceHandle = await driver.instantiateWithImports(componentHandle, imports)

  const api = bindRuntimeGuest(driver, instanceHandle)
  /** @type {import('./bindings-runtime-guest/libduckdb.runtime-guest.d.mts').DuckdbComponentDatabase | undefined} */
  const database = api['duckdb:component/database']
  if (!database) {
    throw new Error(
      "run-core: bindRuntimeGuest returned no 'duckdb:component/database' interface — " +
      'the wasm export surface has drifted from what the bindings expect. Regenerate ' +
      'bindings with `npm run generate` against the current wasm binary.',
    )
  }
  return database
}

// -----------------------------------------------------------------------------
// Instantiate the core component and run a query. Runtime-guest `execute` is a
// synchronous byte-frame call — no JSPI plumbing needed for the plain-query
// path (the wasi-polyfill lane needed JSPI to yield across DoH / ws-gateway
// round-trips inside socket-using extensions; that work is separate).
// -----------------------------------------------------------------------------
export async function runQuery(componentBytes, sql = 'SELECT 42 AS answer, 1 + 1 AS two') {
  const db = await instantiateCore(componentBytes)
  const openRes = await db.open(undefined) // none -> in-memory database
  if (openRes.tag === 'err') {
    const msg = typeof openRes.val === 'string' ? openRes.val : (openRes.val?.val ?? JSON.stringify(openRes.val))
    throw new Error(`run-core: database.open() failed: ${msg}`)
  }
  const conn = openRes.val
  const execRes = await db.execute(conn, sql)
  await db.close(conn)
  if (execRes.tag === 'err') {
    const errPayload = execRes.val
    const msg = typeof errPayload === 'string'
      ? errPayload
      : `${errPayload.tag}: ${errPayload.val}`
    throw new Error(`run-core: database.execute() failed: ${msg}`)
  }
  return execRes.val
}
